// Generated by GitHub Copilot on 2026-03-29
using InterviewCoach.Mcp.PresaleData;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class AskedQuestionsTests
{
    [Fact]
    public async Task AddAskedQuestion_Should_Persist_Question_Metadata()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var askedQuestion = new AskedQuestion
        {
            QuestionText = "What challenges do you need help with?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "challenge"
        };

        var result = await repository.AddAskedQuestionAsync(lead.Id, askedQuestion);

        Assert.NotNull(result);
        Assert.Equal(lead.Id, result.PresaleLeadId);
        Assert.Equal("What challenges do you need help with?", result.QuestionText);
        Assert.Equal("Discovery", result.Phase);
        Assert.Equal("discovery_agent", result.AgentName);
        Assert.Equal(DiscoveryQuestionKind.Initial, result.QuestionKind);
        Assert.Equal(0, result.RoundNumber);
        Assert.Equal("challenge", result.QuestionTopicKey);
        Assert.True(result.AskedAtUtc <= DateTimeOffset.UtcNow);
    }

    [Fact]
    public async Task GetAskedQuestions_Should_Return_Ordered_By_AskedAtUtc()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);

        var question1 = new AskedQuestion
        {
            QuestionText = "First question?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionTopicKey = "first-topic",
            AskedAtUtc = DateTimeOffset.UtcNow.AddMinutes(-2)
        };

        var question2 = new AskedQuestion
        {
            QuestionText = "Second question?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionTopicKey = "second-topic",
            AskedAtUtc = DateTimeOffset.UtcNow.AddMinutes(-1)
        };

        await repository.AddAskedQuestionAsync(lead.Id, question1);
        await repository.AddAskedQuestionAsync(lead.Id, question2);

        var questions = await repository.GetAskedQuestionsAsync(lead.Id);

        var questionsList = questions.ToList();
        Assert.Equal(2, questionsList.Count);
        Assert.Equal("First question?", questionsList[0].QuestionText);
        Assert.Equal("Second question?", questionsList[1].QuestionText);
    }

    [Fact]
    public async Task AddAskedQuestion_With_NonExistent_Lead_Should_Return_Null()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var askedQuestion = new AskedQuestion
        {
            QuestionText = "Test question?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionTopicKey = "test-topic"
        };

        var result = await repository.AddAskedQuestionAsync(Guid.NewGuid(), askedQuestion);

        Assert.Null(result);
    }

    [Fact]
    public async Task Backward_Compatibility_Empty_AskedQuestions_Should_Work()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var questions = await repository.GetAskedQuestionsAsync(lead.Id);

        Assert.Empty(questions);
    }

    [Fact]
    public async Task AddAskedQuestion_With_MissingTopic_AndNegativeRound_Should_Normalize_Values()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var parentId = Guid.NewGuid();
        var askedQuestion = new AskedQuestion
        {
            QuestionText = "Follow-up question?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.FollowUp,
            RoundNumber = -3,
            ParentAskedQuestionId = parentId,
            QuestionTopicKey = string.Empty
        };

        var result = await repository.AddAskedQuestionAsync(lead.Id, askedQuestion);

        Assert.NotNull(result);
        Assert.Equal(DiscoveryQuestionKind.FollowUp, result.QuestionKind);
        Assert.Equal(0, result.RoundNumber);
        Assert.Equal(parentId, result.ParentAskedQuestionId);
        Assert.Equal("unknown", result.QuestionTopicKey);
    }

    [Fact]
    public async Task AddAskedQuestionsBatch_Should_Persist_All_Items_Atomically()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var batch = new List<AskedQuestion>
        {
            new()
            {
                QuestionText = "What challenge are you solving?",
                Phase = "Discovery",
                AgentName = "discovery_agent",
                QuestionKind = DiscoveryQuestionKind.Initial,
                RoundNumber = 0,
                QuestionTopicKey = "challenge"
            },
            new()
            {
                QuestionText = "What timeline do you have?",
                Phase = "Discovery",
                AgentName = "discovery_agent",
                QuestionKind = DiscoveryQuestionKind.Initial,
                RoundNumber = -1,
                QuestionTopicKey = string.Empty
            }
        };

        var result = await repository.AddAskedQuestionsBatchAsync(lead.Id, batch);

        Assert.True(result.Success);
        Assert.Equal(2, result.Questions.Count);

        var persisted = (await repository.GetAskedQuestionsAsync(lead.Id)).ToList();
        Assert.Equal(2, persisted.Count);
        Assert.All(persisted, x => Assert.Equal(lead.Id, x.PresaleLeadId));
        Assert.Contains(persisted, x => x.QuestionTopicKey == "unknown" && x.RoundNumber == 0);
    }

    [Fact]
    public async Task AddAskedQuestionsBatch_With_NonExistent_Lead_Should_NotPersist_AnyItems()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var batch = new List<AskedQuestion>
        {
            new()
            {
                QuestionText = "Question 1",
                Phase = "Discovery",
                AgentName = "discovery_agent",
                QuestionTopicKey = "topic-1"
            },
            new()
            {
                QuestionText = "Question 2",
                Phase = "Discovery",
                AgentName = "discovery_agent",
                QuestionTopicKey = "topic-2"
            }
        };

        var result = await repository.AddAskedQuestionsBatchAsync(Guid.NewGuid(), batch);

        Assert.False(result.Success);
        Assert.Equal("LEAD_NOT_FOUND", result.ErrorCode);
        Assert.Empty(result.Questions);
        Assert.Equal(0, await dbContext.AskedQuestions.CountAsync());
    }

    [Fact]
    public async Task AddAskedQuestionsBatch_With_Duplicate_Retry_Should_NotInsert_Duplicates()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var batch = new List<AskedQuestion>
        {
            new()
            {
                QuestionText = "What challenge are you solving?",
                Phase = "Discovery",
                AgentName = "discovery_agent",
                QuestionKind = DiscoveryQuestionKind.Initial,
                RoundNumber = 0,
                QuestionTopicKey = "challenge"
            },
            new()
            {
                QuestionText = "What timeline do you have?",
                Phase = "Discovery",
                AgentName = "discovery_agent",
                QuestionKind = DiscoveryQuestionKind.Initial,
                RoundNumber = 0,
                QuestionTopicKey = "timeline"
            }
        };

        var first = await repository.AddAskedQuestionsBatchAsync(lead.Id, batch);
        var second = await repository.AddAskedQuestionsBatchAsync(lead.Id, batch);

        Assert.True(first.Success);
        Assert.Equal(2, first.Questions.Count);
        Assert.True(second.Success);
        Assert.Empty(second.Questions);
        Assert.Equal(2, await dbContext.AskedQuestions.CountAsync());
    }

    [Fact]
    public async Task AddAskedQuestion_With_Duplicate_Key_Should_Return_Existing_Record_Without_New_Insert()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);

        var first = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What challenge are you solving?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "challenge"
        });

        var second = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "Rephrased challenge question?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "challenge"
        });

        Assert.NotNull(first);
        Assert.NotNull(second);
        Assert.Equal(first.Id, second.Id);
        Assert.Equal(1, await dbContext.AskedQuestions.CountAsync());
    }

    [Fact]
    public async Task AskedQuestions_Composite_Key_Should_Be_Unique_At_Database_Level()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-unique-index"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        dbContext.AskedQuestions.Add(new AskedQuestion
        {
            Id = Guid.NewGuid(),
            PresaleLeadId = lead.Id,
            QuestionText = "What challenge are you solving?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "challenge",
            AskedAtUtc = DateTimeOffset.UtcNow
        });
        await dbContext.SaveChangesAsync();

        dbContext.AskedQuestions.Add(new AskedQuestion
        {
            Id = Guid.NewGuid(),
            PresaleLeadId = lead.Id,
            QuestionText = "Rephrased challenge question?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "challenge",
            AskedAtUtc = DateTimeOffset.UtcNow
        });

        await Assert.ThrowsAsync<DbUpdateException>(async () => await dbContext.SaveChangesAsync());
    }

}