// Generated by GitHub Copilot on 2026-03-30
using Shouldly;
using Xunit;

namespace InterviewCoach.Agent.Tests;

public class BaohAssistantWorkflowPromptContractTests
{
    [Fact]
    public void Given_BaohWorkflowInstructions_When_Checked_Then_It_Should_Contain_BatchedDiscovery_And_SingleFollowUpRoundRules()
    {
        // Arrange
        var repositoryRoot = ResolveRepositoryRoot();
        var sourcePath = Path.Combine(repositoryRoot, "src", "InterviewCoach.Agent", "AgentDelegateFactory.cs");
        var source = File.ReadAllText(sourcePath);

        // Act
        var containsInitialBatchBuilder = source.Contains("Then call BuildInitialDiscoveryBatch(proposedQuestionsJson, askedQuestionsJson, {{DiscoveryFlowLimits.InitialBatchSize}}).", StringComparison.Ordinal);
        var containsSingleFollowUpRoundCap = source.Contains("Maximum follow-up rounds: {{DiscoveryFlowLimits.MaxFollowUpRounds}}.", StringComparison.Ordinal);
        var containsBatchPersistTool = source.Contains("Call add_asked_questions_batch once with leadId = lead.Id", StringComparison.Ordinal);
        var containsDeterministicParserTool = source.Contains("After user reply, call parse_discovery_reply", StringComparison.Ordinal);
        var containsDeterministicPayloadBuilder = source.Contains("Call BuildAddDiscoveryQuestionPayloads(parseDiscoveryReplyResultJson, askedQuestionsJson)", StringComparison.Ordinal);
        var containsDeterministicTransitionTool = source.Contains("Call evaluate_discovery_transition before any handoff decision.", StringComparison.Ordinal);
        var containsMandatoryCallOrder = source.Contains("Mandatory call order for each discovery turn (do not reorder, do not skip):", StringComparison.Ordinal);
        var buildInitialAppearsOnce = source.Split("Before calling BuildInitialDiscoveryBatch").Length - 1 == 1;

        var contactAgentStart = source.IndexOf("name: \"contact_collection_agent\"", StringComparison.Ordinal);
        var discoveryBuilderPosition = source.IndexOf("Before calling BuildInitialDiscoveryBatch", StringComparison.Ordinal);
        var discoveryBuilderOnlyInDiscoverySection = discoveryBuilderPosition >= 0
            && contactAgentStart > 0
            && discoveryBuilderPosition < contactAgentStart;

        var containsSummaryCompositionTool = source.Contains("Call evaluate_summary_composition before drafting the summary", StringComparison.Ordinal);
        var containsDistilledNarrativeRule = source.Contains("If DistilledNarrativeOnly=true, keep the narrative distilled", StringComparison.Ordinal);
        var containsConditionalUnknownsRule = source.Contains("If IncludeUnknownsSection=true, include an \"Unknowns\" section", StringComparison.Ordinal);

        // Assert
        Assert.True(containsInitialBatchBuilder);
        Assert.True(containsSingleFollowUpRoundCap);
        Assert.True(containsBatchPersistTool);
        Assert.True(containsDeterministicParserTool);
        Assert.True(containsDeterministicPayloadBuilder);
        Assert.True(containsDeterministicTransitionTool);
        Assert.True(containsMandatoryCallOrder);
        Assert.True(buildInitialAppearsOnce);
        Assert.True(discoveryBuilderOnlyInDiscoverySection);
        Assert.True(containsSummaryCompositionTool);
        Assert.True(containsDistilledNarrativeRule);
        Assert.True(containsConditionalUnknownsRule);
    }

    private static string ResolveRepositoryRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null)
        {
            if (File.Exists(Path.Combine(current.FullName, "InterviewCoach.slnx")))
            {
                return current.FullName;
            }

            current = current.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root.");
    }

    [Fact]
    public void Given_IntroductionAgentInstructions_When_Checked_Then_It_Should_Have_ConditionalIntroRule_AndSetup_AndHandoff()
    {
        // Arrange
        var repositoryRoot = ResolveRepositoryRoot();
        var sourcePath = Path.Combine(repositoryRoot, "src", "InterviewCoach.Agent", "AgentDelegateFactory.cs");
        var source = File.ReadAllText(sourcePath);

        // Act
        var containsSetupGetLead = source.Contains("Always call get_presale_lead_by_session before any write.", StringComparison.Ordinal);
        var containsCreateLeadIfMissing = source.Contains("call create_presale_lead with:", StringComparison.Ordinal);
        var containsPhaseUpdateBeforeHandoff = source.Contains("update_presale_lead setting CurrentPhase = Discovery", StringComparison.Ordinal);
        var containsHandoffToDiscovery = source.Contains("hand off to discovery_agent", StringComparison.Ordinal);

        // Assert
        containsSetupGetLead.ShouldBeTrue("introduction_agent must call get_presale_lead_by_session during setup");
        containsCreateLeadIfMissing.ShouldBeTrue("introduction_agent must create a lead when none exists");
        containsPhaseUpdateBeforeHandoff.ShouldBeTrue("introduction_agent must update CurrentPhase to Discovery before handing off");
        containsHandoffToDiscovery.ShouldBeTrue("introduction_agent must hand off to discovery_agent");
    }
}