// Generated by GitHub Copilot on 2026-03-22
using Bunit;

using InterviewCoach.WebUI.Components.Pages.Chat;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class ChatInputComponentTests : TestContext
{
    [Fact]
    public void Given_Default_ChatInput_When_Rendered_Then_Attach_Controls_Are_Visible()
    {
        // Arrange
        JSInterop.Mode = JSRuntimeMode.Loose;

        // Act
        var cut = RenderComponent<ChatInput>();

        // Assert
        cut.FindAll("button.attach").Count.ShouldBe(1);
        cut.FindAll("input[type='file']").Count.ShouldBe(1);
    }

    [Fact]
    public void Given_ChatInput_With_File_Upload_Disabled_When_Rendered_Then_Attach_Controls_Are_Hidden()
    {
        // Arrange
        JSInterop.Mode = JSRuntimeMode.Loose;

        // Act
        var cut = RenderComponent<ChatInput>(parameters => parameters
            .Add(p => p.IncludeFileUpload, false));

        // Assert
        cut.FindAll("button.attach").ShouldBeEmpty();
        cut.FindAll("input[type='file']").ShouldBeEmpty();
    }
}