// Generated by GitHub Copilot on 2026-03-30
using InterviewCoach.Mcp.PresaleData;
using InterviewCoach.Shared.Presale;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class DiscoveryPhaseIntegrationTests
{
    [Fact]
    public async Task Given_DiscoveryAdvances_To_ContactCollection_When_SummaryIsPersisted_And_ExportIsMarked_Then_It_Should_Complete_The_Summarizer_To_Email_Lifecycle_Without_ReExport()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase6-lifecycle-1",
            CurrentPhase = ConversationPhase.Discovery,
            RequestType = RequestType.LegacyModernization,
            CurrentDiscoveryRound = 1,
            FollowUpAskedCount = 4,
            PendingDiscoveryItemsJson = "[\"timeline\"]",
            DiscoveryCompletenessScore = 0.91m,
            DiscoveryCompletenessReason = "unknowns_required",
            Transcript = "Introduction complete\nDiscovery in progress"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var summaryPolicyService = new SummaryCompositionPolicyService(repository);
        var exportTimestamp = new DateTimeOffset(2026, 3, 30, 12, 0, 0, TimeSpan.Zero);

        await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        // Act

        var contactCollectionLead = await repository.GetPresaleLeadAsync(lead.Id);

        await repository.UpdatePresaleLeadAsync(new PresaleLead
        {
            Id = lead.Id,
            CurrentPhase = ConversationPhase.Completed,
            ContactName = "Taylor Morgan",
            ContactCompany = "Contoso",
            ContactEmail = "taylor@contoso.com",
            Transcript = "Contact collection complete"
        });

        var summaryPolicyResult = await summaryPolicyService.EvaluateAsync(new EvaluateSummaryCompositionRequest(
            LeadId: lead.Id,
            UnknownsCompletenessThreshold: 0.85m));

        var summaryText = """
            Challenge: Modernize internal line-of-business systems.
            Goals: Reduce delivery risk and improve delivery cadence.
            Constraints: Budget guardrails remain partially unknown.
            Timeline: Target launch this year.
            Recommended next steps: Review architecture and staffing plan.

            Unknowns:
            - timeline
            """;

        await repository.UpdatePresaleLeadAsync(new PresaleLead
        {
            Id = lead.Id,
            CurrentPhase = ConversationPhase.Completed,
            Summary = summaryText
        });

        var firstExport = await repository.MarkLeadExportedAsync(lead.Id, exportTimestamp);
        var secondExport = await repository.MarkLeadExportedAsync(lead.Id, exportTimestamp.AddMinutes(5));
        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert

        contactCollectionLead.ShouldNotBeNull();
        contactCollectionLead.CurrentPhase.ShouldBe(ConversationPhase.ContactCollection);

        summaryPolicyResult.Success.ShouldBeTrue();
        summaryPolicyResult.IncludeUnknownsSection.ShouldBeTrue();

        firstExport.Success.ShouldBeTrue();
        firstExport.ExportedAt.ShouldBe(exportTimestamp);

        secondExport.Success.ShouldBeFalse();
        secondExport.ErrorCode.ShouldBe("ALREADY_EXPORTED");
        secondExport.ExportedAt.ShouldBe(exportTimestamp);

        updatedLead.ShouldNotBeNull();
        updatedLead.CurrentPhase.ShouldBe(ConversationPhase.Completed);
        updatedLead.ContactName.ShouldBe("Taylor Morgan");
        updatedLead.ContactCompany.ShouldBe("Contoso");
        updatedLead.ContactEmail.ShouldBe("taylor@contoso.com");
        updatedLead.Summary.ShouldBe(summaryText);
        updatedLead.ExportedAt.ShouldBe(exportTimestamp);
    }
}
