// Generated by GitHub Copilot on 2026-03-30
using InterviewCoach.Mcp.PresaleData;
using InterviewCoach.Shared.Presale;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class DiscoveryFollowUpPolicyServiceTests
{
    [Fact]
    public async Task Given_FewerValidProposedFollowUps_ThanBudget_When_EvaluateAsync_Invoked_Then_It_Should_Fill_ToFive_Using_DeterministicSupplementalCandidates()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-0",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 0,
            FollowUpAskedCount = 0,
            PendingDiscoveryItemsJson = "[\"timeline\",\"budget\"]"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var initialBudget = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What budget range do you have?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "budget"
        });

        var sut = new DiscoveryFollowUpPolicyService(repository);

        // Act
        var result = await sut.EvaluateAsync(new EvaluateFollowUpPolicyRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Any hard deadline?", "timeline", initialTimeline!.Id, true),
                new ProposedFollowUpQuestion("Any budget constraints?", "budget", initialBudget!.Id, true)
            ]));

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeTrue();
        result.ApprovedQuestions.Count.ShouldBe(5);
        result.ApprovedQuestions.All(x => x.RoundNumber == 1).ShouldBeTrue();
        result.ApprovedQuestions.Count(x => x.QuestionTopicKey == "timeline").ShouldBe(1);
        result.ApprovedQuestions.Count(x => x.QuestionTopicKey == "budget").ShouldBe(1);
        result.ApprovedQuestions.Select(x => x.QuestionTopicKey).Distinct().Count().ShouldBe(5);
        result.ApprovedQuestions.Count(x => x.QuestionTopicKey is not "timeline" and not "budget").ShouldBe(3);
    }

    [Fact]
    public async Task Given_UnresolvedTopics_And_RemainingBudget_When_EvaluateAsync_Invoked_Then_It_Should_Approve_Only_ValidFollowUps()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-1",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 0,
            FollowUpAskedCount = 0,
            PendingDiscoveryItemsJson = "[\"timeline\",\"budget\",\"scope\"]"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var initialBudget = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What budget range do you have?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "budget"
        });

        var sut = new DiscoveryFollowUpPolicyService(repository);

        // Act
        var result = await sut.EvaluateAsync(new EvaluateFollowUpPolicyRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Timeline details?", "timeline", initialTimeline!.Id, true),
                new ProposedFollowUpQuestion("Budget constraints?", "budget", initialBudget!.Id, true),
                new ProposedFollowUpQuestion("How fixed is project scope?", "scope", initialTimeline.Id, true),
                new ProposedFollowUpQuestion("What tech stack do you prefer?", "tech-stack", initialTimeline.Id, false),
                new ProposedFollowUpQuestion("Do you have a delivery window?", "delivery-window", initialTimeline.Id, false),
                new ProposedFollowUpQuestion("How many stakeholders are involved?", "stakeholders", initialBudget.Id, false)
            ]));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeTrue();
        result.ApprovedQuestions.Count.ShouldBe(5);
        result.ApprovedQuestions.All(x => x.RoundNumber == 1).ShouldBeTrue();
        result.ApprovedQuestions.Any(x => x.QuestionTopicKey == "timeline").ShouldBeTrue();
        result.ApprovedQuestions.Any(x => x.QuestionTopicKey == "budget").ShouldBeTrue();
        result.ApprovedQuestions.Any(x => x.QuestionTopicKey == "scope").ShouldBeTrue();

        updatedLead.ShouldNotBeNull();
        updatedLead.CurrentDiscoveryRound.ShouldBe(1);
        updatedLead.FollowUpAskedCount.ShouldBe(5);
    }

    [Fact]
    public async Task Given_FollowUpLimitsReached_When_EvaluateAsync_Invoked_Then_It_Should_BlockFollowUps_And_Set_UnknownsRequired()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-2",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 1,
            FollowUpAskedCount = 5,
            PendingDiscoveryItemsJson = "[\"timeline\"]"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var sut = new DiscoveryFollowUpPolicyService(repository);

        // Act
        var result = await sut.EvaluateAsync(new EvaluateFollowUpPolicyRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Timeline details?", "timeline", initialTimeline!.Id, true)
            ]));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeFalse();
        result.LimitsReached.ShouldBeTrue();
        result.UnknownsRequired.ShouldBeTrue();
        result.TransitionHint.ShouldBe("limits_reached_unknowns_required");
        result.ApprovedQuestions.Count.ShouldBe(0);

        updatedLead.ShouldNotBeNull();
        updatedLead.DiscoveryCompletenessReason.ShouldNotBeNull();
        updatedLead.DiscoveryCompletenessReason.ShouldContain("unknowns_required");
    }

    [Fact]
    public async Task Given_FollowUpWithoutInitialParent_When_EvaluateAsync_Invoked_Then_It_Should_Ignore_InvalidProposal_And_Use_DeterministicSupplementals()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-3",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 0,
            FollowUpAskedCount = 1,
            PendingDiscoveryItemsJson = "[\"timeline\"]"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var existingFollowUp = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "Any timeline risks?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.FollowUp,
            RoundNumber = 1,
            ParentAskedQuestionId = initialTimeline!.Id,
            QuestionTopicKey = "timeline"
        });

        var sut = new DiscoveryFollowUpPolicyService(repository);

        // Act
        var result = await sut.EvaluateAsync(new EvaluateFollowUpPolicyRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Timeline details?", "timeline", existingFollowUp!.Id, true)
            ]));

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeTrue();
        result.ApprovedQuestions.Count.ShouldBeGreaterThan(0);
        result.ApprovedQuestions.Any(x => x.QuestionTopicKey == "timeline").ShouldBeFalse();
    }

    [Fact]
    public async Task Given_HighCompletenessScore_When_EvaluateAsync_Invoked_With_LimitedBudget_Then_It_Should_Prioritize_Critical_UnresolvedFollowUps()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-4",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 0,
            FollowUpAskedCount = 4,
            PendingDiscoveryItemsJson = "[\"timeline\",\"budget\"]",
            DiscoveryCompletenessScore = 0.90m
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var initialBudget = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What budget range do you have?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "budget"
        });

        var sut = new DiscoveryFollowUpPolicyService(repository);

        // Act
        var result = await sut.EvaluateAsync(new EvaluateFollowUpPolicyRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Any budget refinements?", "budget", initialBudget!.Id, false),
                new ProposedFollowUpQuestion("Any hard timeline deadline?", "timeline", initialTimeline!.Id, true)
            ],
            MaxQuestionsPerRound: 1));

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeTrue();
        result.ApprovedQuestions.Count.ShouldBe(1);
        result.ApprovedQuestions[0].QuestionTopicKey.ShouldBe("timeline");
        result.ApprovedQuestions[0].RoundNumber.ShouldBe(1);
    }
}