// Generated by GitHub Copilot on 2026-03-30
using System.Text.Json;

using InterviewCoach.Agent;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class DiscoveryPayloadBuilderTests
{
    [Fact]
    public void Given_ProposedInitialQuestions_And_ExistingAskedQuestions_When_BuildInitialDiscoveryBatch_Invoked_Then_It_Should_Filter_OverlappingTopics_And_Respect_The_BatchLimit()
    {
        // Arrange
        var proposedQuestionsJson = """
            [
              {
                "QuestionText": "What challenge are you solving?",
                "QuestionTopicKey": "challenge"
              },
              {
                "QuestionText": "What timeline are you targeting?",
                "QuestionTopicKey": "timeline"
              },
              {
                "QuestionText": "Do you have a target delivery date?",
                "QuestionTopicKey": " timeline "
              },
              {
                "QuestionText": "What budget range do you have?",
                "QuestionTopicKey": "budget"
              }
            ]
            """;

        var askedQuestionsJson = """
            [
              {
                "Id": "11111111-1111-1111-1111-111111111111",
                "QuestionText": "What systems are in scope?",
                "QuestionKind": "Initial",
                "RoundNumber": 0,
                "ParentAskedQuestionId": null,
                "QuestionTopicKey": "scope"
              },
              {
                "Id": "22222222-2222-2222-2222-222222222222",
                "QuestionText": "What timeline constraints exist?",
                "QuestionKind": "Initial",
                "RoundNumber": 0,
                "ParentAskedQuestionId": null,
                "QuestionTopicKey": "timeline"
              }
            ]
            """;

        // Act
        var batchJson = DiscoveryPayloadBuilder.BuildInitialDiscoveryBatch(proposedQuestionsJson, askedQuestionsJson, maxQuestions: 3);

        using var document = JsonDocument.Parse(batchJson);
        var items = document.RootElement.EnumerateArray().ToList();

        // Assert
        items.Count.ShouldBe(2);
        items[0].GetProperty("questionText").GetString().ShouldBe("What challenge are you solving?");
        items[0].GetProperty("questionTopicKey").GetString().ShouldBe("challenge");
        items[1].GetProperty("questionText").GetString().ShouldBe("What budget range do you have?");
        items[1].GetProperty("questionTopicKey").GetString().ShouldBe("budget");
    }

    [Fact]
    public void Given_ParsedReply_And_AskedQuestions_When_BuildAddDiscoveryQuestionPayloads_Invoked_Then_It_Should_Return_Deterministic_ExpandedPayloads()
    {
        // Arrange
        var askedQuestion1Id = Guid.Parse("11111111-1111-1111-1111-111111111111");
        var askedQuestion2Id = Guid.Parse("22222222-2222-2222-2222-222222222222");
        var askedQuestion3Id = Guid.Parse("33333333-3333-3333-3333-333333333333");

        var parseResultJson = """
            {
              "Success": true,
              "Items": [
                {
                  "Number": 1,
                  "Answer": "Legacy modernization",
                  "AskedQuestionIds": ["11111111-1111-1111-1111-111111111111"],
                  "CoverageTopicKeys": ["challenge"]
                },
                {
                  "Number": 2,
                  "Answer": "6 months",
                  "AskedQuestionIds": [
                    "22222222-2222-2222-2222-222222222222",
                    "33333333-3333-3333-3333-333333333333"
                  ],
                  "CoverageTopicKeys": ["timeline"]
                }
              ]
            }
            """;

        var askedQuestionsJson = """
            [
              {
                "Id": "11111111-1111-1111-1111-111111111111",
                "QuestionText": "What challenge are you solving?",
                "QuestionKind": "Initial",
                "RoundNumber": 0,
                "ParentAskedQuestionId": null,
                "QuestionTopicKey": "challenge"
              },
              {
                "Id": "22222222-2222-2222-2222-222222222222",
                "QuestionText": "What is your timeline?",
                "QuestionKind": "Initial",
                "RoundNumber": 0,
                "ParentAskedQuestionId": null,
                "QuestionTopicKey": "timeline"
              },
              {
                "Id": "33333333-3333-3333-3333-333333333333",
                "QuestionText": "Any timeline risks?",
                "QuestionKind": "FollowUp",
                "RoundNumber": 1,
                "ParentAskedQuestionId": "22222222-2222-2222-2222-222222222222",
                "QuestionTopicKey": "timeline"
              }
            ]
            """;

        // Act
        var payloadJson = DiscoveryPayloadBuilder.BuildAddDiscoveryQuestionPayloads(parseResultJson, askedQuestionsJson);

        using var document = JsonDocument.Parse(payloadJson);
        var items = document.RootElement.EnumerateArray().ToList();

        // Assert
        items.Count.ShouldBe(3);

        items[0].GetProperty("askedQuestionId").GetGuid().ShouldBe(askedQuestion1Id);
        items[0].GetProperty("question").GetString().ShouldBe("What challenge are you solving?");
        items[0].GetProperty("answer").GetString().ShouldBe("Legacy modernization");
        items[0].GetProperty("questionKind").GetString().ShouldBe("Initial");

        items[1].GetProperty("askedQuestionId").GetGuid().ShouldBe(askedQuestion2Id);
        items[1].GetProperty("questionKind").GetString().ShouldBe("Initial");

        items[2].GetProperty("askedQuestionId").GetGuid().ShouldBe(askedQuestion3Id);
        items[2].GetProperty("questionKind").GetString().ShouldBe("FollowUp");
        items[2].GetProperty("parentAskedQuestionId").GetGuid().ShouldBe(askedQuestion2Id);
    }
}