// Generated by GitHub Copilot on 2026-03-30
using InterviewCoach.Mcp.PresaleData;
using InterviewCoach.Shared.Presale;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class DiscoveryStateTransitionServiceTests
{
    [Fact]
    public async Task Given_RequiredFieldsComplete_And_ExplicitConfirmation_When_EvaluateTransition_Invoked_Then_It_Should_Move_To_ContactCollection()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-transition-1",
            CurrentPhase = ConversationPhase.Discovery
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var sut = new DiscoveryStateTransitionService(repository);

        // Act
        var result = await sut.EvaluateAndApplyAsync(new EvaluateDiscoveryTransitionRequest(
            LeadId: lead.Id,
            RequiredDiscoveryFieldsComplete: true,
            ExplicitConfirmationReceived: true,
            ConfirmationPromptIssued: false,
            PartialResponseDetected: false));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert
        result.ShouldMoveToContactCollection.ShouldBeTrue();
        result.TransitionReason.ShouldBe("completed_with_confirmation");
        result.UsedFallback.ShouldBeFalse();
        result.DiscoveryUserConfirmed.ShouldBeTrue();
        updatedLead.ShouldNotBeNull();
        updatedLead.CurrentPhase.ShouldBe(ConversationPhase.ContactCollection);
        updatedLead.DiscoveryUserConfirmed.ShouldBeTrue();
    }

    [Fact]
    public async Task Given_ConfirmationNotReceived_And_PartialResponsesReachThreshold_When_EvaluateTransition_Invoked_Then_It_Should_Continue_Discovery()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-transition-2",
            CurrentPhase = ConversationPhase.Discovery,
            ConfirmationPromptCount = 1,
            ConsecutivePartialResponseCount = 1,
            PendingDiscoveryItemsJson = "[\"timeline\"]"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var sut = new DiscoveryStateTransitionService(repository);

        // Act
        var result = await sut.EvaluateAndApplyAsync(new EvaluateDiscoveryTransitionRequest(
            LeadId: lead.Id,
            RequiredDiscoveryFieldsComplete: false,
            ExplicitConfirmationReceived: false,
            ConfirmationPromptIssued: true,
            PartialResponseDetected: true));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert
        result.ShouldMoveToContactCollection.ShouldBeFalse();
        result.UsedFallback.ShouldBeFalse();
        result.TransitionReason.ShouldBe("continue_discovery");
        updatedLead.ShouldNotBeNull();
        updatedLead.CurrentPhase.ShouldBe(ConversationPhase.Discovery);
        updatedLead.DiscoveryUserConfirmed.ShouldBeFalse();
    }

    [Fact]
    public async Task Given_RetryResumeScenario_When_EvaluateTransition_Invoked_Then_It_Should_Persist_And_Increment_Counters_Deterministically()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-transition-3",
            CurrentPhase = ConversationPhase.Discovery
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var sut = new DiscoveryStateTransitionService(repository);

        // Act
        var first = await sut.EvaluateAndApplyAsync(new EvaluateDiscoveryTransitionRequest(
            LeadId: lead.Id,
            RequiredDiscoveryFieldsComplete: false,
            ExplicitConfirmationReceived: false,
            ConfirmationPromptIssued: true,
            PartialResponseDetected: true));

        var second = await sut.EvaluateAndApplyAsync(new EvaluateDiscoveryTransitionRequest(
            LeadId: lead.Id,
            RequiredDiscoveryFieldsComplete: false,
            ExplicitConfirmationReceived: false,
            ConfirmationPromptIssued: false,
            PartialResponseDetected: true));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert
        first.ShouldMoveToContactCollection.ShouldBeFalse();
        second.ShouldMoveToContactCollection.ShouldBeFalse();
        updatedLead.ShouldNotBeNull();
        updatedLead.ConfirmationPromptCount.ShouldBe(1);
        updatedLead.ConsecutivePartialResponseCount.ShouldBe(2);
    }

    [Fact]
    public async Task Given_ExplicitConfirmation_And_FollowUpLimitsExhausted_When_EvaluateTransition_Invoked_Then_It_Should_Prioritize_Confirmation_WithoutFallback()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-transition-4",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 1,
            FollowUpAskedCount = 5,
            DiscoveryCompletenessReason = "unknowns_required"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var sut = new DiscoveryStateTransitionService(repository);

        // Act
        var result = await sut.EvaluateAndApplyAsync(new EvaluateDiscoveryTransitionRequest(
            LeadId: lead.Id,
            RequiredDiscoveryFieldsComplete: true,
            ExplicitConfirmationReceived: true,
            ConfirmationPromptIssued: true,
            PartialResponseDetected: false));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert
        result.Success.ShouldBeTrue();
        result.ShouldMoveToContactCollection.ShouldBeTrue();
        result.UsedFallback.ShouldBeFalse();
        result.TransitionReason.ShouldBe("completed_with_confirmation");

        updatedLead.ShouldNotBeNull();
        updatedLead.CurrentPhase.ShouldBe(ConversationPhase.ContactCollection);
        updatedLead.DiscoveryUserConfirmed.ShouldBeTrue();
        updatedLead.DiscoveryCompletenessReason.ShouldContain("unknowns_required");
        updatedLead.DiscoveryCompletenessReason.ShouldNotContain("confirmation_unavailable");
    }
}