// Generated by GitHub Copilot on 2026-03-30
using InterviewCoach.Mcp.PresaleData;
using InterviewCoach.Shared.Presale;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class DiscoveryFollowUpPersistenceServiceTests
{
    [Fact]
    public async Task Given_ApprovedFollowUps_When_EvaluateAndPersistAsync_Invoked_Then_It_Should_Persist_AskedQuestions_And_KeepLeadStateInSync()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-persist-1",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 0,
            FollowUpAskedCount = 3,
            PendingDiscoveryItemsJson = "[\"timeline\",\"budget\"]"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var initialBudget = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What budget range do you have?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "budget"
        });

        var sut = new DiscoveryFollowUpPersistenceService(dbContext);

        // Act
        var result = await sut.EvaluateAndPersistAsync(new EvaluateAndPersistFollowUpsRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Timeline risks?", "timeline", initialTimeline!.Id, true),
                new ProposedFollowUpQuestion("Budget guardrails?", "budget", initialBudget!.Id, true)
            ]));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);
        var askedQuestions = (await repository.GetAskedQuestionsAsync(lead.Id)).ToList();

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeTrue();
        result.PersistedAskedQuestions.Count.ShouldBe(2);
        result.PersistedAskedQuestions.All(x => x.QuestionKind == DiscoveryQuestionKind.FollowUp.ToString()).ShouldBeTrue();
        result.PersistedAskedQuestions.All(x => x.RoundNumber == 1).ShouldBeTrue();

        updatedLead.ShouldNotBeNull();
        updatedLead.CurrentDiscoveryRound.ShouldBe(1);
        updatedLead.FollowUpAskedCount.ShouldBe(5);

        askedQuestions.Count(x => x.QuestionKind == DiscoveryQuestionKind.FollowUp).ShouldBe(2);
    }

    [Fact]
    public async Task Given_RejectedFollowUps_When_EvaluateAndPersistAsync_Invoked_Then_It_Should_NotPersist_AnyNewAskedQuestions()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-persist-2",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 1,
            FollowUpAskedCount = 5,
            PendingDiscoveryItemsJson = "[\"timeline\"]"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var askedBefore = (await repository.GetAskedQuestionsAsync(lead.Id)).Count();
        var sut = new DiscoveryFollowUpPersistenceService(dbContext);

        // Act
        var result = await sut.EvaluateAndPersistAsync(new EvaluateAndPersistFollowUpsRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Timeline risks?", "timeline", initialTimeline!.Id, true)
            ]));

        var askedAfter = (await repository.GetAskedQuestionsAsync(lead.Id)).Count();

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeFalse();
        result.PersistedAskedQuestions.Count.ShouldBe(0);
        askedAfter.ShouldBe(askedBefore);
    }

    [Fact]
    public async Task Given_FollowUpLimitsReached_WithCriticalUnknowns_When_EvaluateAndPersistAsync_Invoked_Then_It_Should_Persist_UnknownsSemantics_ForSummarizerHandoff()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "phase4-persist-3",
            CurrentPhase = ConversationPhase.Discovery,
            CurrentDiscoveryRound = 1,
            FollowUpAskedCount = 5,
            PendingDiscoveryItemsJson = "[\"timeline\"]",
            DiscoveryCompletenessReason = "confirmation_unavailable"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var initialTimeline = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion
        {
            QuestionText = "What timeline are you targeting?",
            Phase = "Discovery",
            AgentName = "discovery_agent",
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0,
            QuestionTopicKey = "timeline"
        });

        var sut = new DiscoveryFollowUpPersistenceService(dbContext);

        // Act
        var result = await sut.EvaluateAndPersistAsync(new EvaluateAndPersistFollowUpsRequest(
            LeadId: lead.Id,
            ProposedQuestions:
            [
                new ProposedFollowUpQuestion("Any timeline blockers?", "timeline", initialTimeline!.Id, true)
            ]));

        var updatedLead = await repository.GetPresaleLeadAsync(lead.Id);

        // Assert
        result.Success.ShouldBeTrue();
        result.AllowFollowUpQuestions.ShouldBeFalse();
        result.UnknownsRequired.ShouldBeTrue();
        result.TransitionHint.ShouldBe("limits_reached_unknowns_required");
        result.PersistedAskedQuestions.Count.ShouldBe(0);

        updatedLead.ShouldNotBeNull();
        updatedLead.DiscoveryCompletenessReason.ShouldContain("confirmation_unavailable");
        updatedLead.DiscoveryCompletenessReason.ShouldContain("unknowns_required");
    }
}