// Generated by GitHub Copilot on 2026-03-30
using InterviewCoach.Mcp.PresaleData;
using InterviewCoach.Shared.Presale;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class DiscoveryReplyParserServiceTests
{
    [Fact]
    public async Task Given_NumberedReply_When_ParseAsync_Invoked_Then_It_Should_Return_Deterministic_MultiMap_Output()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead { Id = Guid.NewGuid(), SessionId = "parse-1", CurrentPhase = ConversationPhase.Discovery };
        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var q1 = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion { QuestionText = "What challenge?", Phase = "Discovery", AgentName = "discovery_agent", QuestionTopicKey = "challenge" });
        var q2 = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion { QuestionText = "What timeline?", Phase = "Discovery", AgentName = "discovery_agent", QuestionTopicKey = "timeline" });
        var q3 = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion { QuestionText = "Any timeline risks?", Phase = "Discovery", AgentName = "discovery_agent", QuestionTopicKey = "timeline", QuestionKind = DiscoveryQuestionKind.FollowUp, RoundNumber = 1, ParentAskedQuestionId = q2!.Id });
        var sut = new DiscoveryReplyParserService(repository);

        // Act
        var result = await sut.ParseAsync(new ParseDiscoveryReplyRequest(
            LeadId: lead.Id,
            UserReply: "1. We are modernizing legacy services.\n2) We need this done in 6 months."));

        // Assert
        result.Success.ShouldBeTrue();
        result.Items.Count.ShouldBe(2);

        var first = result.Items[0];
        first.Number.ShouldBe(1);
        first.AskedQuestionIds.Count.ShouldBe(1);
        first.AskedQuestionIds[0].ShouldBe(q1!.Id);

        var second = result.Items[1];
        second.Number.ShouldBe(2);
        second.AskedQuestionIds.Count.ShouldBe(2);
        second.AskedQuestionIds.ShouldContain(q2!.Id);
        second.AskedQuestionIds.ShouldContain(q3!.Id);
    }

    [Fact]
    public async Task Given_UnnumberedReply_When_ParseAsync_Invoked_Then_It_Should_Create_Single_Deterministic_Item()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead { Id = Guid.NewGuid(), SessionId = "parse-2", CurrentPhase = ConversationPhase.Discovery };
        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var q1 = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion { QuestionText = "What challenge?", Phase = "Discovery", AgentName = "discovery_agent", QuestionTopicKey = "challenge" });
        var sut = new DiscoveryReplyParserService(repository);

        // Act
        var result = await sut.ParseAsync(new ParseDiscoveryReplyRequest(
            LeadId: lead.Id,
            UserReply: "We need help with cloud migration and team enablement."));

        // Assert
        result.Success.ShouldBeTrue();
        result.Items.Count.ShouldBe(1);
        result.Items[0].Number.ShouldBe(1);
        result.Items[0].AskedQuestionIds.Count.ShouldBe(1);
        result.Items[0].AskedQuestionIds[0].ShouldBe(q1!.Id);
    }

    [Fact]
    public async Task Given_AnsweredAskedQuestion_When_ParseAsync_Invoked_With_UnansweredOnly_Then_It_Should_Map_To_Next_Unanswered_Question()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead { Id = Guid.NewGuid(), SessionId = "parse-3", CurrentPhase = ConversationPhase.Discovery };
        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var q1 = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion { QuestionText = "What challenge?", Phase = "Discovery", AgentName = "discovery_agent", QuestionTopicKey = "challenge" });
        var q2 = await repository.AddAskedQuestionAsync(lead.Id, new AskedQuestion { QuestionText = "What timeline?", Phase = "Discovery", AgentName = "discovery_agent", QuestionTopicKey = "timeline" });

        await repository.AddDiscoveryQuestionAsync(lead.Id, new DiscoveryQuestion
        {
            Question = "What challenge?",
            Answer = "Legacy migration",
            AskedQuestionId = q1!.Id,
            QuestionKind = DiscoveryQuestionKind.Initial,
            RoundNumber = 0
        });

        var sut = new DiscoveryReplyParserService(repository);

        // Act
        var result = await sut.ParseAsync(new ParseDiscoveryReplyRequest(
            LeadId: lead.Id,
            UserReply: "1. Six months",
            UseUnansweredOnly: true));

        // Assert
        result.Success.ShouldBeTrue();
        result.Items.Count.ShouldBe(1);
        result.Items[0].AskedQuestionIds.Count.ShouldBe(1);
        result.Items[0].AskedQuestionIds[0].ShouldBe(q2!.Id);
    }
}