// Generated by GitHub Copilot on 2026-03-29
using System.Text.Json;

using InterviewCoach.Mcp.PresaleData;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class PresaleLeadRepositorySerializationTests
{
    [Fact]
    public async Task AddDiscoveryQuestionWithLimit_Result_Should_Serialize_Without_Cycles()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var result = await repository.AddDiscoveryQuestionWithLimitAsync(
            lead.Id,
            new DiscoveryQuestion
            {
                Question = "What challenges do you need help with?",
                Answer = "We need to migrate an on-premise ordering system to the cloud.",
                QuestionKind = DiscoveryQuestionKind.Initial,
                RoundNumber = 0,
                CoverageTopicKeys = "[\"challenge\",\"timeline\"]"
            });

        var exception = Record.Exception(() => JsonSerializer.Serialize(result));

        Assert.Null(exception);

        var json = JsonSerializer.Serialize(result);
        using var document = JsonDocument.Parse(json);

        Assert.True(document.RootElement.TryGetProperty("Question", out var questionElement));
        Assert.True(questionElement.TryGetProperty("PresaleLeadId", out _));
        Assert.True(questionElement.TryGetProperty("QuestionKind", out _));
        Assert.True(questionElement.TryGetProperty("CoverageTopicKeys", out _));
        Assert.False(questionElement.TryGetProperty("PresaleLead", out _));
    }

    [Fact]
    public async Task UpdatePresaleLead_Should_Persist_DiscoveryTracking_Fields()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "session-123"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);

        await repository.UpdatePresaleLeadAsync(new PresaleLead
        {
            Id = lead.Id,
            CurrentPhase = lead.CurrentPhase,
            RequestType = lead.RequestType,
            InitialDiscoveryAskedCount = 4,
            FollowUpAskedCount = 2,
            CurrentDiscoveryRound = 1,
            PendingDiscoveryItemsJson = "[\"constraints\"]",
            AdditionalNotes = "Unmapped details from user message",
            DiscoveryUserConfirmed = true,
            DiscoveryCompletenessScore = 0.8m,
            DiscoveryCompletenessReason = "Missing timeline details"
        });

        var updated = await repository.GetPresaleLeadAsync(lead.Id);

        Assert.NotNull(updated);
        Assert.Equal(4, updated.InitialDiscoveryAskedCount);
        Assert.Equal(2, updated.FollowUpAskedCount);
        Assert.Equal(1, updated.CurrentDiscoveryRound);
        Assert.Equal("[\"constraints\"]", updated.PendingDiscoveryItemsJson);
        Assert.Equal("Unmapped details from user message", updated.AdditionalNotes);
        Assert.True(updated.DiscoveryUserConfirmed);
        Assert.Equal(0.8m, updated.DiscoveryCompletenessScore);
        Assert.Equal("Missing timeline details", updated.DiscoveryCompletenessReason);
    }
}