// Generated by GitHub Copilot on 2026-03-29
using InterviewCoach.Shared.Infrastructure;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class SqliteResourceNamesTests
{
    [Fact]
    public void Interview_And_Presale_Data_Should_Not_Share_The_Same_Sqlite_Resource()
    {
        Assert.NotEqual(SqliteResourceNames.InterviewDataResourceName, SqliteResourceNames.PresaleDataResourceName);
        Assert.NotEqual(SqliteResourceNames.InterviewDataDatabaseFileName, SqliteResourceNames.PresaleDataDatabaseFileName);
    }
}