// Generated by GitHub Copilot on 2026-03-30
using InterviewCoach.Mcp.PresaleData;
using InterviewCoach.Shared.Presale;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

using Shouldly;

using Xunit;

namespace InterviewCoach.Agent.Tests;

public class SummaryCompositionPolicyServiceTests
{
    [Fact]
    public async Task Given_UnknownsRequiredToken_WithPendingTopics_When_EvaluateAsync_Invoked_Then_It_Should_Include_Unknowns_And_Keep_DistilledNarrative()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "summary-policy-1",
            CurrentPhase = ConversationPhase.Completed,
            PendingDiscoveryItemsJson = "[\"timeline\",\"budget\"]",
            DiscoveryCompletenessScore = 0.92m,
            DiscoveryCompletenessReason = "unknowns_required"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var sut = new SummaryCompositionPolicyService(repository);

        // Act
        var result = await sut.EvaluateAsync(new EvaluateSummaryCompositionRequest(
            LeadId: lead.Id,
            UnknownsCompletenessThreshold: 0.85m));

        // Assert
        result.Success.ShouldBeTrue();
        result.IncludeUnknownsSection.ShouldBeTrue();
        result.DistilledNarrativeOnly.ShouldBeTrue();
        result.IncludeAskedQuestionsAppendix.ShouldBeFalse();
        result.DecisionReason.ShouldBe("required_by_unknowns_token");
        result.UnknownTopics.Count.ShouldBe(2);
        result.UnknownsSectionText.ShouldContain("Unknowns");
    }

    [Fact]
    public async Task Given_NoRequiredSignals_When_EvaluateAsync_Invoked_Then_It_Should_NotInclude_Unknowns_And_ShouldRemain_Distilled()
    {
        // Arrange
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<PresaleDataDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var dbContext = new PresaleDataDbContext(options);
        await dbContext.Database.EnsureCreatedAsync();

        var lead = new PresaleLead
        {
            Id = Guid.NewGuid(),
            SessionId = "summary-policy-2",
            CurrentPhase = ConversationPhase.Completed,
            PendingDiscoveryItemsJson = "[\"timeline\"]",
            DiscoveryCompletenessScore = 0.95m,
            DiscoveryCompletenessReason = "completed_with_confirmation"
        };

        dbContext.PresaleLeads.Add(lead);
        await dbContext.SaveChangesAsync();

        var repository = new PresaleLeadRepository(dbContext);
        var sut = new SummaryCompositionPolicyService(repository);

        // Act
        var result = await sut.EvaluateAsync(new EvaluateSummaryCompositionRequest(
            LeadId: lead.Id,
            UnknownsCompletenessThreshold: 0.85m));

        // Assert
        result.Success.ShouldBeTrue();
        result.IncludeUnknownsSection.ShouldBeFalse();
        result.DistilledNarrativeOnly.ShouldBeTrue();
        result.IncludeAskedQuestionsAppendix.ShouldBeFalse();
        result.DecisionReason.ShouldBe("not_required");
        result.UnknownTopics.Count.ShouldBe(0);
        result.UnknownsSectionText.ShouldBe(string.Empty);
    }
}
