// Generated by GitHub Copilot on 2026-03-30
using System.Text.RegularExpressions;

namespace InterviewCoach.Mcp.PresaleData;

public record ParseDiscoveryReplyRequest(
    Guid LeadId,
    string UserReply,
    bool UseUnansweredOnly = true,
    int MaxItems = 5);

public record ParsedDiscoveryAnswerItem(
    int Number,
    string Answer,
    List<Guid> AskedQuestionIds,
    List<string> CoverageTopicKeys);

public record ParseDiscoveryReplyResult(
    bool Success,
    List<ParsedDiscoveryAnswerItem> Items,
    string UnmappedText,
    string? ErrorCode = null,
    string? ErrorMessage = null);

public interface IDiscoveryReplyParserService
{
    Task<ParseDiscoveryReplyResult> ParseAsync(ParseDiscoveryReplyRequest request);
}

public class DiscoveryReplyParserService(IPresaleLeadRepository repository) : IDiscoveryReplyParserService
{
    private static readonly Regex NumberedSegmentRegex = new(
        @"^\s*(\d{1,2})\s*[\.|\)|:|-]\s*(.+?)(?=^\s*\d{1,2}\s*[\.|\)|:|-]\s*|\z)",
        RegexOptions.Multiline | RegexOptions.Singleline | RegexOptions.Compiled);

    public async Task<ParseDiscoveryReplyResult> ParseAsync(ParseDiscoveryReplyRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.UserReply))
        {
            return new ParseDiscoveryReplyResult(
                Success: false,
                Items: [],
                UnmappedText: string.Empty,
                ErrorCode: "EMPTY_REPLY",
                ErrorMessage: "User reply was empty.");
        }

        var lead = await repository.GetPresaleLeadAsync(request.LeadId);
        if (lead is null)
        {
            return new ParseDiscoveryReplyResult(
                Success: false,
                Items: [],
                UnmappedText: request.UserReply,
                ErrorCode: "LEAD_NOT_FOUND",
                ErrorMessage: "Presale lead was not found.");
        }

        var askedQuestions = (await repository.GetAskedQuestionsAsync(request.LeadId))
            .OrderBy(x => x.AskedAtUtc)
            .ToList();

        var answeredAskedIds = (await repository.GetDiscoveryQuestionsAsync(request.LeadId))
            .Where(x => x.AskedQuestionId.HasValue)
            .Select(x => x.AskedQuestionId!.Value)
            .ToHashSet();

        var candidateAskedQuestions = request.UseUnansweredOnly
            ? askedQuestions.Where(x => !answeredAskedIds.Contains(x.Id)).ToList()
            : askedQuestions;

        var cappedCandidates = candidateAskedQuestions
            .Take(Math.Max(1, request.MaxItems))
            .ToList();

        var numberedMatches = NumberedSegmentRegex.Matches(request.UserReply);

        var parsedItems = new List<(int Number, string Answer)>();
        if (numberedMatches.Count > 0)
        {
            foreach (Match match in numberedMatches)
            {
                if (!match.Success)
                {
                    continue;
                }

                var number = int.TryParse(match.Groups[1].Value, out var parsedNumber) ? parsedNumber : parsedItems.Count + 1;
                var answer = match.Groups[2].Value.Trim();
                if (string.IsNullOrWhiteSpace(answer))
                {
                    continue;
                }

                parsedItems.Add((number, answer));
            }
        }
        else
        {
            parsedItems.Add((1, request.UserReply.Trim()));
        }

        var mappedItems = new List<ParsedDiscoveryAnswerItem>();
        foreach (var item in parsedItems)
        {
            var index = Math.Max(0, item.Number - 1);
            AskedQuestion? primaryAskedQuestion = null;
            if (index < cappedCandidates.Count)
            {
                primaryAskedQuestion = cappedCandidates[index];
            }

            var mappedAskedIds = new List<Guid>();
            var coverageTopics = new List<string>();

            if (primaryAskedQuestion is not null)
            {
                var topicKey = NormalizeTopicKey(primaryAskedQuestion.QuestionTopicKey);
                var sameTopicAskedQuestions = cappedCandidates
                    .Where(x => string.Equals(NormalizeTopicKey(x.QuestionTopicKey), topicKey, StringComparison.OrdinalIgnoreCase))
                    .Select(x => x.Id)
                    .Distinct()
                    .ToList();

                mappedAskedIds.AddRange(sameTopicAskedQuestions);

                if (!string.Equals(topicKey, "unknown", StringComparison.OrdinalIgnoreCase))
                {
                    coverageTopics.Add(topicKey);
                }
            }

            mappedItems.Add(new ParsedDiscoveryAnswerItem(
                Number: item.Number,
                Answer: item.Answer,
                AskedQuestionIds: mappedAskedIds,
                CoverageTopicKeys: coverageTopics.Distinct(StringComparer.OrdinalIgnoreCase).ToList()));
        }

        return new ParseDiscoveryReplyResult(
            Success: true,
            Items: mappedItems,
            UnmappedText: string.Empty);
    }

    private static string NormalizeTopicKey(string? topicKey)
    {
        return string.IsNullOrWhiteSpace(topicKey)
            ? "unknown"
            : topicKey.Trim().ToLowerInvariant();
    }
}
