// Generated by GitHub Copilot on 2026-03-30
using System.Text.Json;

using Microsoft.EntityFrameworkCore;

namespace InterviewCoach.Mcp.PresaleData;

public record ProposedFollowUpQuestion(
    string QuestionText,
    string QuestionTopicKey,
    Guid ParentInitialAskedQuestionId,
    bool IsCritical);

public record ApprovedFollowUpQuestion(
    string QuestionText,
    string QuestionTopicKey,
    Guid ParentInitialAskedQuestionId,
    string QuestionKind,
    int RoundNumber);

public record EvaluateFollowUpPolicyRequest(
    Guid LeadId,
    List<ProposedFollowUpQuestion> ProposedQuestions,
    int MaxFollowUpQuestions = 5,
    int MaxFollowUpRounds = 1,
    int MaxQuestionsPerRound = 5);

public record EvaluateFollowUpPolicyResult(
    bool Success,
    bool AllowFollowUpQuestions,
    bool LimitsReached,
    bool UnknownsRequired,
    string TransitionHint,
    int CurrentDiscoveryRound,
    int FollowUpAskedCount,
    List<ApprovedFollowUpQuestion> ApprovedQuestions,
    string? ErrorCode = null,
    string? ErrorMessage = null);

public record PersistedFollowUpAskedQuestion(
    Guid Id,
    string QuestionText,
    string QuestionTopicKey,
    string QuestionKind,
    int RoundNumber,
    Guid ParentInitialAskedQuestionId);

public record EvaluateAndPersistFollowUpsRequest(
    Guid LeadId,
    List<ProposedFollowUpQuestion> ProposedQuestions,
    int MaxFollowUpQuestions = 5,
    int MaxFollowUpRounds = 1,
    int MaxQuestionsPerRound = 5);

public record EvaluateAndPersistFollowUpsResult(
    bool Success,
    bool AllowFollowUpQuestions,
    bool LimitsReached,
    bool UnknownsRequired,
    string TransitionHint,
    int CurrentDiscoveryRound,
    int FollowUpAskedCount,
    List<PersistedFollowUpAskedQuestion> PersistedAskedQuestions,
    string? ErrorCode = null,
    string? ErrorMessage = null);

public interface IDiscoveryFollowUpPolicyService
{
    Task<EvaluateFollowUpPolicyResult> EvaluateAsync(EvaluateFollowUpPolicyRequest request);
}

public interface IDiscoveryFollowUpPersistenceService
{
    Task<EvaluateAndPersistFollowUpsResult> EvaluateAndPersistAsync(EvaluateAndPersistFollowUpsRequest request);
}

public class DiscoveryFollowUpPolicyService(IPresaleLeadRepository repository) : IDiscoveryFollowUpPolicyService
{
    public async Task<EvaluateFollowUpPolicyResult> EvaluateAsync(EvaluateFollowUpPolicyRequest request)
    {
        var lead = await repository.GetPresaleLeadAsync(request.LeadId);
        if (lead is null)
        {
            return new EvaluateFollowUpPolicyResult(
                Success: false,
                AllowFollowUpQuestions: false,
                LimitsReached: false,
                UnknownsRequired: false,
                TransitionHint: "lead_not_found",
                CurrentDiscoveryRound: 0,
                FollowUpAskedCount: 0,
                ApprovedQuestions: [],
                ErrorCode: "LEAD_NOT_FOUND",
                ErrorMessage: "Presale lead was not found.");
        }

        var askedQuestions = (await repository.GetAskedQuestionsAsync(lead.Id)).ToDictionary(x => x.Id, x => x);
        var evaluation = DiscoveryFollowUpPolicyEvaluator.Evaluate(lead, askedQuestions, request.ProposedQuestions, request.MaxFollowUpQuestions, request.MaxFollowUpRounds, request.MaxQuestionsPerRound);

        lead.CurrentDiscoveryRound = evaluation.NextRoundNumber;
        lead.FollowUpAskedCount = evaluation.NextFollowUpAskedCount;

        if (evaluation.UnknownsRequired)
        {
            lead.DiscoveryCompletenessReason = AppendReasonToken(lead.DiscoveryCompletenessReason, "unknowns_required");
        }

        await repository.UpdatePresaleLeadAsync(lead);

        return new EvaluateFollowUpPolicyResult(
            Success: true,
            AllowFollowUpQuestions: evaluation.AllowFollowUpQuestions,
            LimitsReached: evaluation.LimitsReached,
            UnknownsRequired: evaluation.UnknownsRequired,
            TransitionHint: evaluation.TransitionHint,
            CurrentDiscoveryRound: lead.CurrentDiscoveryRound,
            FollowUpAskedCount: lead.FollowUpAskedCount,
            ApprovedQuestions: evaluation.ApprovedQuestions);
    }

    internal static string AppendReasonToken(string? current, string token)
    {
        if (string.IsNullOrWhiteSpace(current))
        {
            return token;
        }

        if (current.Contains(token, StringComparison.OrdinalIgnoreCase))
        {
            return current;
        }

        return $"{current};{token}";
    }
}

public class DiscoveryFollowUpPersistenceService(PresaleDataDbContext dbContext) : IDiscoveryFollowUpPersistenceService
{
    public async Task<EvaluateAndPersistFollowUpsResult> EvaluateAndPersistAsync(EvaluateAndPersistFollowUpsRequest request)
    {
        await using var tx = await dbContext.Database.BeginTransactionAsync();

        var lead = await dbContext.PresaleLeads.SingleOrDefaultAsync(x => x.Id == request.LeadId);
        if (lead is null)
        {
            await tx.RollbackAsync();

            return new EvaluateAndPersistFollowUpsResult(
                Success: false,
                AllowFollowUpQuestions: false,
                LimitsReached: false,
                UnknownsRequired: false,
                TransitionHint: "lead_not_found",
                CurrentDiscoveryRound: 0,
                FollowUpAskedCount: 0,
                PersistedAskedQuestions: [],
                ErrorCode: "LEAD_NOT_FOUND",
                ErrorMessage: "Presale lead was not found.");
        }

        var askedQuestions = await dbContext.AskedQuestions.Where(x => x.PresaleLeadId == request.LeadId)
                                   .ToDictionaryAsync(x => x.Id, x => x);

        var evaluation = DiscoveryFollowUpPolicyEvaluator.Evaluate(lead, askedQuestions, request.ProposedQuestions, request.MaxFollowUpQuestions, request.MaxFollowUpRounds, request.MaxQuestionsPerRound);

        if (!evaluation.AllowFollowUpQuestions || evaluation.ApprovedQuestions.Count == 0)
        {
            if (evaluation.UnknownsRequired)
            {
                lead.DiscoveryCompletenessReason = DiscoveryFollowUpPolicyService.AppendReasonToken(lead.DiscoveryCompletenessReason, "unknowns_required");
                dbContext.PresaleLeads.Update(lead);
                await dbContext.SaveChangesAsync();
                await tx.CommitAsync();
            }
            else
            {
                await tx.RollbackAsync();
            }

            return new EvaluateAndPersistFollowUpsResult(
                Success: true,
                AllowFollowUpQuestions: evaluation.AllowFollowUpQuestions,
                LimitsReached: evaluation.LimitsReached,
                UnknownsRequired: evaluation.UnknownsRequired,
                TransitionHint: evaluation.TransitionHint,
                CurrentDiscoveryRound: lead.CurrentDiscoveryRound,
                FollowUpAskedCount: lead.FollowUpAskedCount,
                PersistedAskedQuestions: []);
        }

        var now = DateTimeOffset.UtcNow;
        var persistedAskedQuestions = new List<PersistedFollowUpAskedQuestion>();
        foreach (var approvedQuestion in evaluation.ApprovedQuestions)
        {
            var entity = new AskedQuestion
            {
                Id = Guid.NewGuid(),
                PresaleLeadId = lead.Id,
                QuestionText = approvedQuestion.QuestionText,
                Phase = "Discovery",
                AgentName = "discovery_agent",
                QuestionKind = DiscoveryQuestionKind.FollowUp,
                RoundNumber = approvedQuestion.RoundNumber,
                ParentAskedQuestionId = approvedQuestion.ParentInitialAskedQuestionId,
                QuestionTopicKey = approvedQuestion.QuestionTopicKey,
                AskedAtUtc = now
            };

            dbContext.AskedQuestions.Add(entity);
            persistedAskedQuestions.Add(new PersistedFollowUpAskedQuestion(
                Id: entity.Id,
                QuestionText: entity.QuestionText,
                QuestionTopicKey: entity.QuestionTopicKey,
                QuestionKind: entity.QuestionKind.ToString(),
                RoundNumber: entity.RoundNumber,
                ParentInitialAskedQuestionId: entity.ParentAskedQuestionId!.Value));
        }

        lead.CurrentDiscoveryRound = evaluation.NextRoundNumber;
        lead.FollowUpAskedCount = evaluation.NextFollowUpAskedCount;
        lead.UpdatedAt = now;

        if (evaluation.UnknownsRequired)
        {
            lead.DiscoveryCompletenessReason = DiscoveryFollowUpPolicyService.AppendReasonToken(lead.DiscoveryCompletenessReason, "unknowns_required");
        }

        dbContext.PresaleLeads.Update(lead);
        await dbContext.SaveChangesAsync();
        await tx.CommitAsync();

        return new EvaluateAndPersistFollowUpsResult(
            Success: true,
            AllowFollowUpQuestions: true,
            LimitsReached: evaluation.LimitsReached,
            UnknownsRequired: evaluation.UnknownsRequired,
            TransitionHint: evaluation.TransitionHint,
            CurrentDiscoveryRound: lead.CurrentDiscoveryRound,
            FollowUpAskedCount: lead.FollowUpAskedCount,
            PersistedAskedQuestions: persistedAskedQuestions);
    }
}

internal sealed record FollowUpPolicyEvaluation(
    bool AllowFollowUpQuestions,
    bool LimitsReached,
    bool UnknownsRequired,
    string TransitionHint,
    int NextRoundNumber,
    int NextFollowUpAskedCount,
    List<ApprovedFollowUpQuestion> ApprovedQuestions);

internal static class DiscoveryFollowUpPolicyEvaluator
{
    private static readonly (string TopicKey, string QuestionText)[] SupplementalFollowUpPool =
    [
        ("team-size", "How many people from your side will be involved in delivery and reviews?"),
        ("delivery-model", "Do you prefer fixed-scope milestones or a continuous delivery model?"),
        ("tech-stack", "Are there preferred technologies or platforms we should align with?"),
        ("dependencies", "Are there external dependencies or systems we need to coordinate with?"),
        ("success-metrics", "What outcomes will define success for this initiative?")
    ];

    internal static FollowUpPolicyEvaluation Evaluate(
        PresaleLead lead,
        IReadOnlyDictionary<Guid, AskedQuestion> askedQuestions,
        IEnumerable<ProposedFollowUpQuestion> proposedQuestions,
        int maxFollowUpQuestions,
        int maxFollowUpRounds,
        int maxQuestionsPerRound)
    {
        var normalizedUnresolvedTopics = ParseTopicList(lead.PendingDiscoveryItemsJson);

        var remainingQuestionBudget = Math.Max(0, maxFollowUpQuestions - lead.FollowUpAskedCount);
        var remainingRoundBudget = Math.Max(0, maxFollowUpRounds - lead.CurrentDiscoveryRound);
        var limitsReached = remainingQuestionBudget == 0 || remainingRoundBudget == 0;

        if (limitsReached)
        {
            var unknownsRequiredOnLimits = HasCriticalUnresolved(proposedQuestions, normalizedUnresolvedTopics);

            return new FollowUpPolicyEvaluation(
                AllowFollowUpQuestions: false,
                LimitsReached: true,
                UnknownsRequired: unknownsRequiredOnLimits,
                TransitionHint: unknownsRequiredOnLimits ? "limits_reached_unknowns_required" : "limits_reached",
                NextRoundNumber: lead.CurrentDiscoveryRound,
                NextFollowUpAskedCount: lead.FollowUpAskedCount,
                ApprovedQuestions: []);
        }

        var targetRound = Math.Min(maxFollowUpRounds, Math.Max(1, lead.CurrentDiscoveryRound + 1));
        var maxApprovedCount = Math.Min(Math.Max(1, maxQuestionsPerRound), remainingQuestionBudget);

        var completenessScore = decimal.ToDouble(Math.Clamp(lead.DiscoveryCompletenessScore, 0m, 1m));

        var candidateQuestions = proposedQuestions
            .Where(x => !string.IsNullOrWhiteSpace(x.QuestionText))
            .Where(x => askedQuestions.TryGetValue(x.ParentInitialAskedQuestionId, out var parent) && parent.QuestionKind == DiscoveryQuestionKind.Initial)
            .GroupBy(x => NormalizeTopicKey(x.QuestionTopicKey))
            .Select(x => x.First())
            .ToList();

        var supplementalCandidates = BuildSupplementalCandidates(askedQuestions, candidateQuestions, normalizedUnresolvedTopics)
            .ToList();

        candidateQuestions.AddRange(supplementalCandidates);

        var unresolvedCandidates = candidateQuestions
            .Where(x => normalizedUnresolvedTopics.Count == 0 || normalizedUnresolvedTopics.Contains(NormalizeTopicKey(x.QuestionTopicKey)))
            .OrderBy(x => ComputeDiagnosticPriorityRank(x, completenessScore))
            .ThenBy(x => NormalizeTopicKey(x.QuestionTopicKey))
            .ToList();

        var nonUnresolvedCandidates = candidateQuestions
            .Where(x => !normalizedUnresolvedTopics.Contains(NormalizeTopicKey(x.QuestionTopicKey)))
            .OrderBy(x => ComputeDiagnosticPriorityRank(x, completenessScore))
            .ThenBy(x => NormalizeTopicKey(x.QuestionTopicKey))
            .ToList();

        var selectedCandidates = unresolvedCandidates
            .Concat(nonUnresolvedCandidates)
            .Take(maxApprovedCount)
            .ToList();

        var approvedQuestions = selectedCandidates
            .Select(x => new ApprovedFollowUpQuestion(
                QuestionText: x.QuestionText.Trim(),
                QuestionTopicKey: NormalizeTopicKey(x.QuestionTopicKey),
                ParentInitialAskedQuestionId: x.ParentInitialAskedQuestionId,
                QuestionKind: DiscoveryQuestionKind.FollowUp.ToString(),
                RoundNumber: targetRound))
            .ToList();

        if (approvedQuestions.Count == 0)
        {
            return new FollowUpPolicyEvaluation(
                AllowFollowUpQuestions: false,
                LimitsReached: false,
                UnknownsRequired: false,
                TransitionHint: "no_valid_followups",
                NextRoundNumber: lead.CurrentDiscoveryRound,
                NextFollowUpAskedCount: lead.FollowUpAskedCount,
                ApprovedQuestions: []);
        }

        var nextFollowUpAskedCount = lead.FollowUpAskedCount + approvedQuestions.Count;
        var nowLimitsReached = targetRound >= maxFollowUpRounds || nextFollowUpAskedCount >= maxFollowUpQuestions;
        var unknownsRequired = nowLimitsReached && HasCriticalUnresolved(proposedQuestions, normalizedUnresolvedTopics);

        return new FollowUpPolicyEvaluation(
            AllowFollowUpQuestions: true,
            LimitsReached: nowLimitsReached,
            UnknownsRequired: unknownsRequired,
            TransitionHint: unknownsRequired ? "approved_followups_limits_reached_unknowns_required" : "approved_followups",
            NextRoundNumber: targetRound,
            NextFollowUpAskedCount: nextFollowUpAskedCount,
            ApprovedQuestions: approvedQuestions);
    }

    private static HashSet<string> ParseTopicList(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return [];
        }

        try
        {
            var topics = JsonSerializer.Deserialize<List<string>>(json) ?? [];

            return topics
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .Select(NormalizeTopicKey)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);
        }
        catch
        {
            return [];
        }
    }

    private static bool HasCriticalUnresolved(IEnumerable<ProposedFollowUpQuestion> proposedQuestions, HashSet<string> unresolvedTopics)
    {
        return proposedQuestions.Any(x => x.IsCritical && unresolvedTopics.Contains(NormalizeTopicKey(x.QuestionTopicKey)));
    }

    private static int ComputeDiagnosticPriorityRank(ProposedFollowUpQuestion question, double completenessScore)
    {
        // When completeness is high, remaining follow-up budget is focused on critical unknowns first.
        if (completenessScore >= 0.75d)
        {
            return question.IsCritical ? 0 : 2;
        }

        // When completeness is lower, criticals still lead but non-criticals are closer in priority.
        return question.IsCritical ? 0 : 1;
    }

    private static string NormalizeTopicKey(string? topic)
    {
        return string.IsNullOrWhiteSpace(topic)
            ? "unknown"
            : topic.Trim().ToLowerInvariant();
    }

    private static IEnumerable<ProposedFollowUpQuestion> BuildSupplementalCandidates(
        IReadOnlyDictionary<Guid, AskedQuestion> askedQuestions,
        IReadOnlyCollection<ProposedFollowUpQuestion> existingCandidates,
        IReadOnlySet<string> unresolvedTopics)
    {
        var initialParentsByTopic = askedQuestions.Values
            .Where(x => x.QuestionKind == DiscoveryQuestionKind.Initial)
            .GroupBy(x => NormalizeTopicKey(x.QuestionTopicKey))
            .ToDictionary(x => x.Key, x => x.First().Id, StringComparer.OrdinalIgnoreCase);

        if (initialParentsByTopic.Count == 0)
        {
            return [];
        }

        var fallbackParentId = initialParentsByTopic.Values.First();
        var usedTopics = existingCandidates
            .Select(x => NormalizeTopicKey(x.QuestionTopicKey))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        return SupplementalFollowUpPool
            .Select(poolItem =>
            {
                var topicKey = NormalizeTopicKey(poolItem.TopicKey);
                var parentId = initialParentsByTopic.TryGetValue(topicKey, out var matchingParentId)
                    ? matchingParentId
                    : fallbackParentId;

                return new ProposedFollowUpQuestion(
                    QuestionText: poolItem.QuestionText,
                    QuestionTopicKey: topicKey,
                    ParentInitialAskedQuestionId: parentId,
                    IsCritical: unresolvedTopics.Contains(topicKey));
            })
            .Where(x => !usedTopics.Contains(NormalizeTopicKey(x.QuestionTopicKey)));
    }
}
