// Generated by GitHub Copilot on 2026-03-30
using InterviewCoach.Shared.Presale;

namespace InterviewCoach.Mcp.PresaleData;

public record EvaluateDiscoveryTransitionRequest(
    Guid LeadId,
    bool RequiredDiscoveryFieldsComplete,
    bool ExplicitConfirmationReceived,
    bool ConfirmationPromptIssued,
    bool PartialResponseDetected,
    int MaxConfirmationPrompts = 2,
    int MaxConsecutivePartialResponses = 2,
    int MaxFollowUpRounds = 1,
    int MaxFollowUpQuestions = 5);

public record EvaluateDiscoveryTransitionResult(
    bool Success,
    bool ShouldMoveToContactCollection,
    bool UsedFallback,
    bool DiscoveryUserConfirmed,
    string TransitionReason,
    int ConfirmationPromptCount,
    int ConsecutivePartialResponseCount,
    ConversationPhase CurrentPhase,
    string? ErrorCode = null,
    string? ErrorMessage = null);

public interface IDiscoveryStateTransitionService
{
    Task<EvaluateDiscoveryTransitionResult> EvaluateAndApplyAsync(EvaluateDiscoveryTransitionRequest request);
}

public class DiscoveryStateTransitionService(IPresaleLeadRepository repository) : IDiscoveryStateTransitionService
{
    public async Task<EvaluateDiscoveryTransitionResult> EvaluateAndApplyAsync(EvaluateDiscoveryTransitionRequest request)
    {
        var lead = await repository.GetPresaleLeadAsync(request.LeadId);
        if (lead is null)
        {
            return new EvaluateDiscoveryTransitionResult(
                Success: false,
                ShouldMoveToContactCollection: false,
                UsedFallback: false,
                DiscoveryUserConfirmed: false,
                TransitionReason: "lead_not_found",
                ConfirmationPromptCount: 0,
                ConsecutivePartialResponseCount: 0,
                CurrentPhase: ConversationPhase.Introduction,
                ErrorCode: "LEAD_NOT_FOUND",
                ErrorMessage: "Presale lead was not found.");
        }

        var nextConfirmationPromptCount = lead.ConfirmationPromptCount + (request.ConfirmationPromptIssued ? 1 : 0);
        var nextConsecutivePartialResponses = request.PartialResponseDetected
            ? lead.ConsecutivePartialResponseCount + 1
            : 0;

        var followUpExhausted = lead.CurrentDiscoveryRound >= request.MaxFollowUpRounds && lead.FollowUpAskedCount >= request.MaxFollowUpQuestions;

        var confirmationSatisfied = request.RequiredDiscoveryFieldsComplete && request.ExplicitConfirmationReceived;

        if (confirmationSatisfied)
        {
            lead.DiscoveryUserConfirmed = true;
            lead.ConfirmationPromptCount = nextConfirmationPromptCount;
            lead.ConsecutivePartialResponseCount = nextConsecutivePartialResponses;
            lead.CurrentPhase = ConversationPhase.ContactCollection;

            await repository.UpdatePresaleLeadAsync(lead);

            return new EvaluateDiscoveryTransitionResult(
                Success: true,
                ShouldMoveToContactCollection: true,
                UsedFallback: false,
                DiscoveryUserConfirmed: true,
                TransitionReason: "completed_with_confirmation",
                ConfirmationPromptCount: lead.ConfirmationPromptCount,
                ConsecutivePartialResponseCount: lead.ConsecutivePartialResponseCount,
                CurrentPhase: lead.CurrentPhase);
        }

        var fallbackRequired = followUpExhausted;

        if (fallbackRequired)
        {
            lead.DiscoveryUserConfirmed = false;
            lead.ConfirmationPromptCount = nextConfirmationPromptCount;
            lead.ConsecutivePartialResponseCount = nextConsecutivePartialResponses;
            lead.CurrentPhase = ConversationPhase.ContactCollection;
            lead.DiscoveryCompletenessReason = AppendReasonToken(lead.DiscoveryCompletenessReason, "confirmation_unavailable");

            await repository.UpdatePresaleLeadAsync(lead);

            return new EvaluateDiscoveryTransitionResult(
                Success: true,
                ShouldMoveToContactCollection: true,
                UsedFallback: true,
                DiscoveryUserConfirmed: false,
                TransitionReason: "followup_limits_reached",
                ConfirmationPromptCount: lead.ConfirmationPromptCount,
                ConsecutivePartialResponseCount: lead.ConsecutivePartialResponseCount,
                CurrentPhase: lead.CurrentPhase);
        }

        lead.DiscoveryUserConfirmed = false;
        lead.ConfirmationPromptCount = nextConfirmationPromptCount;
        lead.ConsecutivePartialResponseCount = nextConsecutivePartialResponses;

        await repository.UpdatePresaleLeadAsync(lead);

        return new EvaluateDiscoveryTransitionResult(
            Success: true,
            ShouldMoveToContactCollection: false,
            UsedFallback: false,
            DiscoveryUserConfirmed: false,
            TransitionReason: "continue_discovery",
            ConfirmationPromptCount: lead.ConfirmationPromptCount,
            ConsecutivePartialResponseCount: lead.ConsecutivePartialResponseCount,
            CurrentPhase: lead.CurrentPhase);
    }

    private static string AppendReasonToken(string? current, string token)
    {
        if (string.IsNullOrWhiteSpace(current))
        {
            return token;
        }

        if (current.Contains(token, StringComparison.OrdinalIgnoreCase))
        {
            return current;
        }

        return $"{current};{token}";
    }
}
