// Generated by GitHub Copilot on 2026-03-29
using System.Text;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace InterviewCoach.Mcp.PresaleData;

public interface IPresaleLeadRepository
{
    Task<PresaleLead> CreatePresaleLeadAsync(PresaleLead lead);
    Task<PresaleLead?> GetPresaleLeadAsync(Guid id);
    Task<PresaleLead?> GetPresaleLeadBySessionIdAsync(string sessionId);
    Task<PresaleLead?> UpdatePresaleLeadAsync(PresaleLead lead);
    Task<MarkLeadExportedResult> MarkLeadExportedAsync(Guid leadId, DateTimeOffset exportedAtUtc);
    Task<DiscoveryQuestion?> AddDiscoveryQuestionAsync(Guid leadId, DiscoveryQuestion question);
    Task<DiscoveryQuestionAddResult> AddDiscoveryQuestionWithLimitAsync(Guid leadId, DiscoveryQuestion question, int maxQuestions = 5);
    Task<IEnumerable<DiscoveryQuestion>> GetDiscoveryQuestionsAsync(Guid leadId);
    Task<AskedQuestion?> AddAskedQuestionAsync(Guid leadId, AskedQuestion askedQuestion);
    Task<AskedQuestionBatchAddResult> AddAskedQuestionsBatchAsync(Guid leadId, IReadOnlyList<AskedQuestion> askedQuestions);
    Task<IEnumerable<AskedQuestion>> GetAskedQuestionsAsync(Guid leadId);
}

public record DiscoveryQuestionAddResult(bool Success, string? ErrorCode, string? ErrorMessage, int CurrentCount, DiscoveryQuestion? Question);
public record MarkLeadExportedResult(bool Success, string? ErrorCode, string? ErrorMessage, DateTimeOffset? ExportedAt);
public record AskedQuestionBatchAddResult(bool Success, string? ErrorCode, string? ErrorMessage, IReadOnlyList<AskedQuestion> Questions);

public class PresaleLeadRepository(PresaleDataDbContext db) : IPresaleLeadRepository
{
    public async Task<PresaleLead> CreatePresaleLeadAsync(PresaleLead lead)
    {
        lead.UpdatedAt = DateTimeOffset.UtcNow;

        var added = await db.PresaleLeads.AddAsync(lead);
        await db.SaveChangesAsync();

        return added.Entity;
    }

    public async Task<PresaleLead?> GetPresaleLeadAsync(Guid id)
    {
        return await db.PresaleLeads.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id);
    }

    public async Task<PresaleLead?> GetPresaleLeadBySessionIdAsync(string sessionId)
    {
        return await db.PresaleLeads.AsNoTracking().SingleOrDefaultAsync(x => x.SessionId == sessionId);
    }

    public async Task<PresaleLead?> UpdatePresaleLeadAsync(PresaleLead lead)
    {
        var record = await db.PresaleLeads.SingleOrDefaultAsync(x => x.Id == lead.Id);
        if (record is null)
        {
            return default;
        }

        record.CurrentPhase = lead.CurrentPhase;
        record.RequestType = lead.RequestType;
        record.InitialDiscoveryAskedCount = Math.Max(record.InitialDiscoveryAskedCount, lead.InitialDiscoveryAskedCount);
        record.FollowUpAskedCount = Math.Max(record.FollowUpAskedCount, lead.FollowUpAskedCount);
        record.CurrentDiscoveryRound = Math.Max(record.CurrentDiscoveryRound, lead.CurrentDiscoveryRound);
        record.PendingDiscoveryItemsJson = lead.PendingDiscoveryItemsJson ?? record.PendingDiscoveryItemsJson;
        record.AdditionalNotes = lead.AdditionalNotes ?? record.AdditionalNotes;
        record.DiscoveryUserConfirmed = record.DiscoveryUserConfirmed || lead.DiscoveryUserConfirmed;
        record.ConfirmationPromptCount = Math.Max(record.ConfirmationPromptCount, lead.ConfirmationPromptCount);
        record.ConsecutivePartialResponseCount = Math.Max(record.ConsecutivePartialResponseCount, lead.ConsecutivePartialResponseCount);
        record.DiscoveryCompletenessScore = lead.DiscoveryCompletenessScore > 0 ? lead.DiscoveryCompletenessScore : record.DiscoveryCompletenessScore;
        record.DiscoveryCompletenessReason = lead.DiscoveryCompletenessReason ?? record.DiscoveryCompletenessReason;
        record.Summary = lead.Summary ?? record.Summary;
        record.ContactName = lead.ContactName ?? record.ContactName;
        record.ContactEmail = lead.ContactEmail ?? record.ContactEmail;
        record.ContactCompany = lead.ContactCompany ?? record.ContactCompany;
        record.ContactPhone = lead.ContactPhone ?? record.ContactPhone;
        record.ExportedAt = lead.ExportedAt ?? record.ExportedAt;
        record.UpdatedAt = DateTimeOffset.UtcNow;

        record.Transcript = AppendTranscript(record.Transcript, lead.Transcript);

        await db.PresaleLeads.Where(x => x.Id == lead.Id)
                            .ExecuteUpdateAsync(x => x.SetProperty(p => p.CurrentPhase, record.CurrentPhase)
                                                      .SetProperty(p => p.RequestType, record.RequestType)
                                                      .SetProperty(p => p.InitialDiscoveryAskedCount, record.InitialDiscoveryAskedCount)
                                                      .SetProperty(p => p.FollowUpAskedCount, record.FollowUpAskedCount)
                                                      .SetProperty(p => p.CurrentDiscoveryRound, record.CurrentDiscoveryRound)
                                                      .SetProperty(p => p.PendingDiscoveryItemsJson, record.PendingDiscoveryItemsJson)
                                                      .SetProperty(p => p.AdditionalNotes, record.AdditionalNotes)
                                                      .SetProperty(p => p.DiscoveryUserConfirmed, record.DiscoveryUserConfirmed)
                                                      .SetProperty(p => p.ConfirmationPromptCount, record.ConfirmationPromptCount)
                                                      .SetProperty(p => p.ConsecutivePartialResponseCount, record.ConsecutivePartialResponseCount)
                                                      .SetProperty(p => p.DiscoveryCompletenessScore, record.DiscoveryCompletenessScore)
                                                      .SetProperty(p => p.DiscoveryCompletenessReason, record.DiscoveryCompletenessReason)
                                                      .SetProperty(p => p.Transcript, record.Transcript)
                                                      .SetProperty(p => p.Summary, record.Summary)
                                                      .SetProperty(p => p.ContactName, record.ContactName)
                                                      .SetProperty(p => p.ContactEmail, record.ContactEmail)
                                                      .SetProperty(p => p.ContactCompany, record.ContactCompany)
                                                      .SetProperty(p => p.ContactPhone, record.ContactPhone)
                                                      .SetProperty(p => p.ExportedAt, record.ExportedAt)
                                                      .SetProperty(p => p.UpdatedAt, record.UpdatedAt));

        db.Entry(record).State = EntityState.Detached;

        return record;
    }

    public async Task<DiscoveryQuestion?> AddDiscoveryQuestionAsync(Guid leadId, DiscoveryQuestion question)
    {
        var result = await AddDiscoveryQuestionWithLimitAsync(leadId, question, 5);

        return result.Question;
    }

    public async Task<MarkLeadExportedResult> MarkLeadExportedAsync(Guid leadId, DateTimeOffset exportedAtUtc)
    {
        var affected = await db.PresaleLeads.Where(x => x.Id == leadId && x.ExportedAt == null)
                                            .ExecuteUpdateAsync(x => x.SetProperty(p => p.ExportedAt, exportedAtUtc)
                                                                      .SetProperty(p => p.UpdatedAt, DateTimeOffset.UtcNow));

        if (affected == 1)
        {
            return new MarkLeadExportedResult(true, null, null, exportedAtUtc);
        }

        var existingLead = await db.PresaleLeads.AsNoTracking().SingleOrDefaultAsync(x => x.Id == leadId);
        if (existingLead is null)
        {
            return new MarkLeadExportedResult(false, "LEAD_NOT_FOUND", "Presale lead was not found.", null);
        }

        return new MarkLeadExportedResult(false, "ALREADY_EXPORTED", "Presale lead was already exported.", existingLead.ExportedAt);
    }

    public async Task<DiscoveryQuestionAddResult> AddDiscoveryQuestionWithLimitAsync(Guid leadId, DiscoveryQuestion question, int maxQuestions = 5)
    {
        await using var tx = await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);

        var now = DateTimeOffset.UtcNow;
        var affected = await db.PresaleLeads.Where(x => x.Id == leadId && x.DiscoveryQuestionCount < maxQuestions)
                                            .ExecuteUpdateAsync(x => x.SetProperty(p => p.DiscoveryQuestionCount, p => p.DiscoveryQuestionCount + 1)
                                                                      .SetProperty(p => p.UpdatedAt, now));

        if (affected == 0)
        {
            var existingLead = await db.PresaleLeads.SingleOrDefaultAsync(x => x.Id == leadId);
            if (existingLead is null)
            {
                await tx.RollbackAsync();

                return new DiscoveryQuestionAddResult(false, "LEAD_NOT_FOUND", "Presale lead was not found.", 0, null);
            }

            await tx.RollbackAsync();

            return new DiscoveryQuestionAddResult(false, "DISCOVERY_LIMIT_REACHED", $"Discovery question limit of {maxQuestions} has been reached.", existingLead.DiscoveryQuestionCount, null);
        }

        var lead = await db.PresaleLeads.SingleAsync(x => x.Id == leadId);

        question.PresaleLeadId = leadId;
        question.Id = question.Id == Guid.Empty ? Guid.NewGuid() : question.Id;
        question.Sequence = lead.DiscoveryQuestionCount;
        question.RoundNumber = Math.Max(0, question.RoundNumber);
        question.CreatedAt = now;

        var added = await db.DiscoveryQuestions.AddAsync(question);
        await db.SaveChangesAsync();
        await tx.CommitAsync();

        return new DiscoveryQuestionAddResult(true, null, null, lead.DiscoveryQuestionCount, added.Entity);
    }

    public async Task<IEnumerable<DiscoveryQuestion>> GetDiscoveryQuestionsAsync(Guid leadId)
    {
        return await db.DiscoveryQuestions.Where(x => x.PresaleLeadId == leadId)
                                          .OrderBy(x => x.Sequence)
                                          .ToListAsync();
    }

    public async Task<AskedQuestion?> AddAskedQuestionAsync(Guid leadId, AskedQuestion askedQuestion)
    {
        var leadExists = await db.PresaleLeads.AnyAsync(x => x.Id == leadId);
        if (!leadExists)
        {
            return default;
        }

        askedQuestion.PresaleLeadId = leadId;
        askedQuestion.Id = askedQuestion.Id == Guid.Empty ? Guid.NewGuid() : askedQuestion.Id;
        askedQuestion.RoundNumber = Math.Max(0, askedQuestion.RoundNumber);
        askedQuestion.QuestionTopicKey = string.IsNullOrWhiteSpace(askedQuestion.QuestionTopicKey)
            ? "unknown"
            : askedQuestion.QuestionTopicKey.Trim().ToLowerInvariant();

        var existing = await db.AskedQuestions
            .SingleOrDefaultAsync(x => x.PresaleLeadId == leadId
                                    && x.QuestionTopicKey == askedQuestion.QuestionTopicKey
                                    && x.RoundNumber == askedQuestion.RoundNumber);
        if (existing is not null)
        {
            return existing;
        }

        askedQuestion.AskedAtUtc = DateTimeOffset.UtcNow;

        var added = await db.AskedQuestions.AddAsync(askedQuestion);
        try
        {
            await db.SaveChangesAsync();
        }
        catch (DbUpdateException ex) when (IsUniqueConstraintViolation(ex))
        {
            var concurrentExisting = await db.AskedQuestions
                .SingleOrDefaultAsync(x => x.PresaleLeadId == leadId
                                        && x.QuestionTopicKey == askedQuestion.QuestionTopicKey
                                        && x.RoundNumber == askedQuestion.RoundNumber);
            if (concurrentExisting is not null)
            {
                return concurrentExisting;
            }

            throw;
        }

        return added.Entity;
    }

    public async Task<AskedQuestionBatchAddResult> AddAskedQuestionsBatchAsync(Guid leadId, IReadOnlyList<AskedQuestion> askedQuestions)
    {
        if (askedQuestions.Count == 0)
        {
            return new AskedQuestionBatchAddResult(true, null, null, []);
        }

        await using var tx = await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);

        var leadExists = await db.PresaleLeads.AnyAsync(x => x.Id == leadId);
        if (!leadExists)
        {
            await tx.RollbackAsync();

            return new AskedQuestionBatchAddResult(false, "LEAD_NOT_FOUND", "Presale lead was not found.", []);
        }

        var now = DateTimeOffset.UtcNow;
        var normalized = new List<AskedQuestion>(askedQuestions.Count);
        foreach (var askedQuestion in askedQuestions)
        {
            askedQuestion.PresaleLeadId = leadId;
            askedQuestion.Id = askedQuestion.Id == Guid.Empty ? Guid.NewGuid() : askedQuestion.Id;
            askedQuestion.RoundNumber = Math.Max(0, askedQuestion.RoundNumber);
            askedQuestion.QuestionTopicKey = string.IsNullOrWhiteSpace(askedQuestion.QuestionTopicKey)
                ? "unknown"
                : askedQuestion.QuestionTopicKey.Trim().ToLowerInvariant();
            askedQuestion.AskedAtUtc = now;
            normalized.Add(askedQuestion);
        }

        var distinctByKey = normalized
            .GroupBy(x => (x.QuestionTopicKey, x.RoundNumber))
            .Select(x => x.First())
            .ToList();

        var rounds = distinctByKey.Select(x => x.RoundNumber).Distinct().ToList();
        var topics = distinctByKey.Select(x => x.QuestionTopicKey).Distinct(StringComparer.OrdinalIgnoreCase).ToList();

        var existingKeys = await db.AskedQuestions
            .Where(x => x.PresaleLeadId == leadId && rounds.Contains(x.RoundNumber) && topics.Contains(x.QuestionTopicKey))
            .Select(x => new { x.QuestionTopicKey, x.RoundNumber })
            .ToListAsync();

        var existingSet = existingKeys
            .Select(x => (x.QuestionTopicKey, x.RoundNumber))
            .ToHashSet();

        var toInsert = distinctByKey
            .Where(x => !existingSet.Contains((x.QuestionTopicKey, x.RoundNumber)))
            .ToList();

        if (toInsert.Count == 0)
        {
            await tx.RollbackAsync();

            return new AskedQuestionBatchAddResult(true, null, null, []);
        }

        await db.AskedQuestions.AddRangeAsync(toInsert);
        try
        {
            await db.SaveChangesAsync();
            await tx.CommitAsync();

            return new AskedQuestionBatchAddResult(true, null, null, toInsert);
        }
        catch (DbUpdateException ex) when (IsUniqueConstraintViolation(ex))
        {
            await tx.RollbackAsync();

            var keys = toInsert
                .Select(x => (x.QuestionTopicKey, x.RoundNumber))
                .ToHashSet();

            var recoveryRounds = keys.Select(x => x.RoundNumber).Distinct().ToList();
            var recoveryTopics = keys.Select(x => x.QuestionTopicKey).Distinct(StringComparer.OrdinalIgnoreCase).ToList();

            var recovered = await db.AskedQuestions
                .Where(x => x.PresaleLeadId == leadId && recoveryRounds.Contains(x.RoundNumber) && recoveryTopics.Contains(x.QuestionTopicKey))
                .ToListAsync();

            var recoveredForKeys = recovered
                .Where(x => keys.Contains((x.QuestionTopicKey, x.RoundNumber)))
                .ToList();

            return new AskedQuestionBatchAddResult(true, null, null, recoveredForKeys);
        }
    }

    public async Task<IEnumerable<AskedQuestion>> GetAskedQuestionsAsync(Guid leadId)
    {
        var askedQuestions = await db.AskedQuestions.Where(x => x.PresaleLeadId == leadId)
                                                    .ToListAsync();

        askedQuestions.Sort((left, right) => left.AskedAtUtc.CompareTo(right.AskedAtUtc));

        return askedQuestions;
    }

    private static string? AppendTranscript(string? existingTranscript, string? newTranscript)
    {
        if (string.IsNullOrWhiteSpace(newTranscript))
        {
            return existingTranscript;
        }

        var sb = new StringBuilder();
        sb.AppendLine(existingTranscript ?? string.Empty);
        sb.AppendLine();
        sb.AppendLine(newTranscript);

        return sb.ToString();
    }

    private static bool IsUniqueConstraintViolation(DbUpdateException ex)
    {
        return ex.InnerException is SqliteException sqliteException
            && sqliteException.SqliteErrorCode == 19;
    }
}
