// Generated by GitHub Copilot on 2026-03-29
using System.Text.Json.Serialization;

using InterviewCoach.Shared.Presale;

using Microsoft.EntityFrameworkCore;

namespace InterviewCoach.Mcp.PresaleData;

public enum DiscoveryQuestionKind
{
    Initial = 0,
    FollowUp = 1
}

public class PresaleLead
{
    public Guid Id { get; set; }
    public string SessionId { get; set; } = string.Empty;
    public ConversationPhase CurrentPhase { get; set; } = ConversationPhase.Introduction;
    public RequestType RequestType { get; set; } = RequestType.Unknown;
    public int DiscoveryQuestionCount { get; set; }
    public int InitialDiscoveryAskedCount { get; set; }
    public int FollowUpAskedCount { get; set; }
    public int CurrentDiscoveryRound { get; set; }
    public string? PendingDiscoveryItemsJson { get; set; }
    public string? AdditionalNotes { get; set; }
    public bool DiscoveryUserConfirmed { get; set; }
    public int ConfirmationPromptCount { get; set; }
    public int ConsecutivePartialResponseCount { get; set; }
    public decimal DiscoveryCompletenessScore { get; set; }
    public string? DiscoveryCompletenessReason { get; set; }
    public string? Transcript { get; set; }
    public string? Summary { get; set; }
    public string? ContactName { get; set; }
    public string? ContactEmail { get; set; }
    public string? ContactCompany { get; set; }
    public string? ContactPhone { get; set; }
    public DateTimeOffset? ExportedAt { get; set; }
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;

    public ICollection<DiscoveryQuestion> DiscoveryQuestions { get; set; } = new List<DiscoveryQuestion>();
    public ICollection<AskedQuestion> AskedQuestions { get; set; } = new List<AskedQuestion>();
}

public class DiscoveryQuestion
{
    public Guid Id { get; set; }
    public Guid PresaleLeadId { get; set; }
    public int Sequence { get; set; }
    public string Question { get; set; } = string.Empty;
    public string Answer { get; set; } = string.Empty;
    public Guid? AskedQuestionId { get; set; }
    public DiscoveryQuestionKind QuestionKind { get; set; } = DiscoveryQuestionKind.Initial;
    public int RoundNumber { get; set; }
    public Guid? ParentAskedQuestionId { get; set; }
    public string? CoverageTopicKeys { get; set; }
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    [JsonIgnore]
    public PresaleLead PresaleLead { get; set; } = null!;
}

public class AskedQuestion
{
    public Guid Id { get; set; }
    public Guid PresaleLeadId { get; set; }
    public string QuestionText { get; set; } = string.Empty;
    public string Phase { get; set; } = string.Empty;
    public string AgentName { get; set; } = string.Empty;
    public DiscoveryQuestionKind QuestionKind { get; set; } = DiscoveryQuestionKind.Initial;
    public int RoundNumber { get; set; }
    public Guid? ParentAskedQuestionId { get; set; }
    public string QuestionTopicKey { get; set; } = string.Empty;
    public DateTimeOffset AskedAtUtc { get; set; } = DateTimeOffset.UtcNow;

    [JsonIgnore]
    public PresaleLead PresaleLead { get; set; } = null!;
}

public class PresaleDataDbContext(DbContextOptions<PresaleDataDbContext> options) : DbContext(options)
{
    public DbSet<PresaleLead> PresaleLeads { get; set; } = null!;
    public DbSet<DiscoveryQuestion> DiscoveryQuestions { get; set; } = null!;
    public DbSet<AskedQuestion> AskedQuestions { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PresaleLead>()
                    .ToTable("PresaleLeads")
                    .HasKey(x => x.Id);

        modelBuilder.Entity<PresaleLead>().Property(x => x.Id).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.SessionId).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.CurrentPhase).HasConversion<string>().IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.RequestType).HasConversion<string>().IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.DiscoveryQuestionCount).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.InitialDiscoveryAskedCount).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.FollowUpAskedCount).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.CurrentDiscoveryRound).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.PendingDiscoveryItemsJson);
        modelBuilder.Entity<PresaleLead>().Property(x => x.AdditionalNotes);
        modelBuilder.Entity<PresaleLead>().Property(x => x.DiscoveryUserConfirmed).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.ConfirmationPromptCount).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.ConsecutivePartialResponseCount).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.DiscoveryCompletenessScore).HasPrecision(5, 2).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.DiscoveryCompletenessReason);
        modelBuilder.Entity<PresaleLead>().Property(x => x.Transcript);
        modelBuilder.Entity<PresaleLead>().Property(x => x.Summary);
        modelBuilder.Entity<PresaleLead>().Property(x => x.ContactName);
        modelBuilder.Entity<PresaleLead>().Property(x => x.ContactEmail);
        modelBuilder.Entity<PresaleLead>().Property(x => x.ContactCompany);
        modelBuilder.Entity<PresaleLead>().Property(x => x.ContactPhone);
        modelBuilder.Entity<PresaleLead>().Property(x => x.ExportedAt);
        modelBuilder.Entity<PresaleLead>().Property(x => x.CreatedAt).IsRequired();
        modelBuilder.Entity<PresaleLead>().Property(x => x.UpdatedAt).IsRequired();
        modelBuilder.Entity<PresaleLead>().HasIndex(x => x.SessionId).IsUnique();

        modelBuilder.Entity<DiscoveryQuestion>()
                    .ToTable("DiscoveryQuestions")
                    .HasKey(x => x.Id);

        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.Id).IsRequired();
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.PresaleLeadId).IsRequired();
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.Sequence).IsRequired();
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.Question).IsRequired();
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.Answer).IsRequired();
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.AskedQuestionId);
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.QuestionKind).HasConversion<string>().IsRequired();
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.RoundNumber).IsRequired();
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.ParentAskedQuestionId);
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.CoverageTopicKeys);
        modelBuilder.Entity<DiscoveryQuestion>().Property(x => x.CreatedAt).IsRequired();

        modelBuilder.Entity<DiscoveryQuestion>()
                    .HasOne(x => x.PresaleLead)
                    .WithMany(x => x.DiscoveryQuestions)
                    .HasForeignKey(x => x.PresaleLeadId)
                    .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<DiscoveryQuestion>()
                    .HasIndex(x => new { x.PresaleLeadId, x.Sequence })
                    .IsUnique();

        modelBuilder.Entity<AskedQuestion>()
                    .ToTable("AskedQuestions")
                    .HasKey(x => x.Id);

        modelBuilder.Entity<AskedQuestion>().Property(x => x.Id).IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.PresaleLeadId).IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.QuestionText).IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.Phase).IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.AgentName).IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.QuestionKind).HasConversion<string>().IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.RoundNumber).IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.ParentAskedQuestionId);
        modelBuilder.Entity<AskedQuestion>().Property(x => x.QuestionTopicKey).IsRequired();
        modelBuilder.Entity<AskedQuestion>().Property(x => x.AskedAtUtc).IsRequired();

        modelBuilder.Entity<AskedQuestion>()
                    .HasOne(x => x.PresaleLead)
                    .WithMany(x => x.AskedQuestions)
                    .HasForeignKey(x => x.PresaleLeadId)
                    .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<AskedQuestion>()
                    .HasIndex(x => new { x.PresaleLeadId, x.AskedAtUtc });

        modelBuilder.Entity<AskedQuestion>()
                    .HasIndex(x => new { x.PresaleLeadId, x.QuestionTopicKey, x.RoundNumber })
                    .IsUnique();

        modelBuilder.Entity<AskedQuestion>()
                    .HasIndex(x => x.ParentAskedQuestionId);

        modelBuilder.Entity<DiscoveryQuestion>()
                    .HasIndex(x => x.AskedQuestionId);

        modelBuilder.Entity<DiscoveryQuestion>()
                    .HasIndex(x => x.ParentAskedQuestionId);
    }
}
