// Generated by GitHub Copilot on 2026-03-29
using System.ComponentModel;

using ModelContextProtocol.Server;

namespace InterviewCoach.Mcp.PresaleData;

public interface IPresaleLeadTool
{
    Task<PresaleLead> CreatePresaleLeadAsync(PresaleLead lead);
    Task<PresaleLead?> GetPresaleLeadAsync(Guid id);
    Task<PresaleLead?> GetPresaleLeadBySessionIdAsync(string sessionId);
    Task<PresaleLead?> UpdatePresaleLeadAsync(PresaleLead lead);
    Task<MarkLeadExportedResult> MarkPresaleLeadExportedAsync(Guid leadId, DateTimeOffset exportedAtUtc);
    Task<DiscoveryQuestion?> AddDiscoveryQuestionAsync(Guid leadId, DiscoveryQuestion question);
    Task<DiscoveryQuestionAddResult> AddDiscoveryQuestionWithLimitAsync(Guid leadId, DiscoveryQuestion question, int maxQuestions = 5);
    Task<IEnumerable<DiscoveryQuestion>> GetDiscoveryQuestionsAsync(Guid leadId);
    Task<AskedQuestion?> AddAskedQuestionAsync(Guid leadId, AskedQuestion askedQuestion);
    Task<AskedQuestionBatchAddResult> AddAskedQuestionsBatchAsync(Guid leadId, IReadOnlyList<AskedQuestion> askedQuestions);
    Task<IEnumerable<AskedQuestion>> GetAskedQuestionsAsync(Guid leadId);
}

[McpServerToolType]
public class PresaleLeadTool(
    IPresaleLeadRepository repository,
    ISummaryCompositionPolicyService summaryCompositionPolicyService,
    ILogger<PresaleLeadTool> logger) : IPresaleLeadTool
{
    [McpServerTool(Name = "create_presale_lead", Title = "Create a presale lead")]
    [Description("Creates a presale lead record in the database.")]
    public async Task<PresaleLead> CreatePresaleLeadAsync(
        [Description("The presale lead details")] PresaleLead lead)
    {
        var result = await repository.CreatePresaleLeadAsync(lead);

        logger.LogInformation("Created presale lead with ID '{id}'", result.Id);

        return result;
    }

    [McpServerTool(Name = "get_presale_lead", Title = "Get a presale lead by ID")]
    [Description("Gets a presale lead from the database by ID.")]
    public async Task<PresaleLead?> GetPresaleLeadAsync(
        [Description("The ID of the presale lead")] Guid id)
    {
        var lead = await repository.GetPresaleLeadAsync(id);
        if (lead is null)
        {
            logger.LogWarning("Presale lead with ID '{id}' not found.", id);

            return default;
        }

        logger.LogInformation("Retrieved presale lead with ID '{id}'", id);

        return lead;
    }

    [McpServerTool(Name = "get_presale_lead_by_session", Title = "Get a presale lead by session ID")]
    [Description("Gets a presale lead from the database by session ID.")]
    public async Task<PresaleLead?> GetPresaleLeadBySessionIdAsync(
        [Description("The web chat session ID associated with the lead")] string sessionId)
    {
        var lead = await repository.GetPresaleLeadBySessionIdAsync(sessionId);
        if (lead is null)
        {
            logger.LogWarning("Presale lead with Session ID '{sessionId}' not found.", sessionId);

            return default;
        }

        logger.LogInformation("Retrieved presale lead with Session ID '{sessionId}'", sessionId);

        return lead;
    }

    [McpServerTool(Name = "update_presale_lead", Title = "Update a presale lead")]
    [Description("Updates a presale lead in the database.")]
    public async Task<PresaleLead?> UpdatePresaleLeadAsync(
        [Description("The updated presale lead details")] PresaleLead lead)
    {
        var updated = await repository.UpdatePresaleLeadAsync(lead);
        if (updated is null)
        {
            logger.LogWarning("Presale lead with ID '{id}' not found.", lead.Id);

            return default;
        }

        logger.LogInformation("Updated presale lead with ID '{id}'", lead.Id);

        return updated;
    }

    [McpServerTool(Name = "mark_presale_lead_exported", Title = "Mark lead exported once")]
    [Description("Atomically marks a lead as exported if and only if it has not already been exported.")]
    public async Task<MarkLeadExportedResult> MarkPresaleLeadExportedAsync(
        [Description("The presale lead ID")] Guid leadId,
        [Description("UTC timestamp for export event")] DateTimeOffset exportedAtUtc)
    {
        var result = await repository.MarkLeadExportedAsync(leadId, exportedAtUtc);
        if (!result.Success)
        {
            logger.LogWarning("Failed to mark lead '{leadId}' exported. ErrorCode={errorCode}", leadId, result.ErrorCode);
        }
        else
        {
            logger.LogInformation("Marked lead '{leadId}' exported at {exportedAtUtc}", leadId, exportedAtUtc);
        }

        return result;
    }

    [McpServerTool(Name = "add_discovery_question", Title = "Add discovery question and answer")]
    [Description("Adds a discovery question/answer record for a lead.")]
    public async Task<DiscoveryQuestion?> AddDiscoveryQuestionAsync(
        [Description("The presale lead ID")] Guid leadId,
        [Description("The discovery question and answer details")] DiscoveryQuestion question)
    {
        var added = await repository.AddDiscoveryQuestionAsync(leadId, question);
        if (added is null)
        {
            logger.LogWarning("Unable to add discovery question for lead '{leadId}' because the lead was not found.", leadId);

            return default;
        }

        logger.LogInformation("Added discovery question '{questionId}' for lead '{leadId}'", added.Id, leadId);

        return added;
    }

    [McpServerTool(Name = "add_discovery_question_with_limit", Title = "Add discovery question with hard cap")]
    [Description("Atomically adds a discovery question and increments the lead count while rejecting insertions beyond the configured cap.")]
    public async Task<DiscoveryQuestionAddResult> AddDiscoveryQuestionWithLimitAsync(
        [Description("The presale lead ID")] Guid leadId,
        [Description("The discovery question and answer details")] DiscoveryQuestion question,
        [Description("Maximum allowed discovery question count for the lead")] int maxQuestions = 5)
    {
        var result = await repository.AddDiscoveryQuestionWithLimitAsync(leadId, question, maxQuestions);
        if (!result.Success)
        {
            logger.LogWarning("Discovery insert rejected for lead '{leadId}': {errorCode}", leadId, result.ErrorCode);
        }
        else
        {
            logger.LogInformation("Added capped discovery question '{questionId}' for lead '{leadId}' at count {count}", result.Question!.Id, leadId, result.CurrentCount);
        }

        return result;
    }

    [McpServerTool(Name = "get_discovery_questions", Title = "Get discovery questions for a lead")]
    [Description("Gets all discovery question/answer records for a lead.")]
    public async Task<IEnumerable<DiscoveryQuestion>> GetDiscoveryQuestionsAsync(
        [Description("The presale lead ID")] Guid leadId)
    {
        var questions = await repository.GetDiscoveryQuestionsAsync(leadId);

        logger.LogInformation("Retrieved {count} discovery records for lead '{leadId}'", questions.Count(), leadId);

        return questions;
    }

    [McpServerTool(Name = "add_asked_question", Title = "Add asked question metadata")]
    [Description("Adds metadata for a question that was asked to the lead.")]
    public async Task<AskedQuestion?> AddAskedQuestionAsync(
        [Description("The presale lead ID")] Guid leadId,
        [Description("The asked question metadata")] AskedQuestion askedQuestion)
    {
        var added = await repository.AddAskedQuestionAsync(leadId, askedQuestion);
        if (added is null)
        {
            logger.LogWarning("Unable to add asked question for lead '{leadId}' because the lead was not found.", leadId);

            return default;
        }

        logger.LogInformation("Added asked question '{questionId}' for lead '{leadId}'", added.Id, leadId);

        return added;
    }

    [McpServerTool(Name = "add_asked_questions_batch", Title = "Add asked question metadata batch")]
    [Description("Atomically adds asked-question metadata records for a lead in one operation.")]
    public async Task<AskedQuestionBatchAddResult> AddAskedQuestionsBatchAsync(
        [Description("The presale lead ID")] Guid leadId,
        [Description("The asked question metadata list")] IReadOnlyList<AskedQuestion> askedQuestions)
    {
        var result = await repository.AddAskedQuestionsBatchAsync(leadId, askedQuestions);
        if (!result.Success)
        {
            logger.LogWarning("Unable to add asked-question batch for lead '{leadId}'. ErrorCode={errorCode}", leadId, result.ErrorCode);
        }
        else
        {
            logger.LogInformation("Added {count} asked questions for lead '{leadId}' in one batch", result.Questions.Count, leadId);
        }

        return result;
    }

    [McpServerTool(Name = "get_asked_questions", Title = "Get asked questions for a lead")]
    [Description("Gets all asked question metadata records for a lead.")]
    public async Task<IEnumerable<AskedQuestion>> GetAskedQuestionsAsync(
        [Description("The presale lead ID")] Guid leadId)
    {
        var questions = await repository.GetAskedQuestionsAsync(leadId);

        logger.LogInformation("Retrieved {count} asked question records for lead '{leadId}'", questions.Count(), leadId);

        return questions;
    }
}
