// Generated by GitHub Copilot on 2026-03-29
using System.Reflection;

using InterviewCoach.Mcp.PresaleData;
using InterviewCoach.Shared.Infrastructure;

using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();
builder.AddSqliteConnection(SqliteResourceNames.PresaleDataResourceName);

//var presaleConnectionString = builder.Configuration.GetConnectionString(SqliteResourceNames.PresaleDataResourceName)
//    ?? throw new InvalidOperationException($"Missing connection string for {SqliteResourceNames.PresaleDataResourceName}.");

//using (var bootstrapConnection = new SqliteConnection(presaleConnectionString))
//{
//    // Create the SQLite file early so sqlite_web bind-mounts a file, not a directory.
//    bootstrapConnection.Open();
//}

builder.Services.AddDbContext<PresaleDataDbContext>((sp, options) =>
    options.UseSqlite(sp.GetRequiredService<SqliteConnection>()));
builder.Services.AddScoped<IPresaleLeadRepository, PresaleLeadRepository>();
builder.Services.AddScoped<IDiscoveryReplyParserService, DiscoveryReplyParserService>();
builder.Services.AddScoped<IDiscoveryFollowUpPolicyService, DiscoveryFollowUpPolicyService>();
builder.Services.AddScoped<IDiscoveryFollowUpPersistenceService, DiscoveryFollowUpPersistenceService>();
builder.Services.AddScoped<IDiscoveryStateTransitionService, DiscoveryStateTransitionService>();
builder.Services.AddScoped<ISummaryCompositionPolicyService, SummaryCompositionPolicyService>();

builder.Services.AddMcpServer()
                .WithHttpTransport(o => o.Stateless = true)
                .WithToolsFromAssembly(Assembly.GetEntryAssembly());

var app = builder.Build();

app.MapDefaultEndpoints();

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<PresaleDataDbContext>();
    dbContext.Database.EnsureCreated();
}

if (app.Environment.IsDevelopment() == false)
{
    app.UseHttpsRedirection();
}

app.MapMcp("/mcp");

await app.RunAsync();
