// Generated by GitHub Copilot on 2026-03-30
using System.Text.Json;

namespace InterviewCoach.Mcp.PresaleData;

public record EvaluateSummaryCompositionRequest(
    Guid LeadId,
    decimal UnknownsCompletenessThreshold = 0.85m,
    int MaxUnknownTopics = 5);

public record EvaluateSummaryCompositionResult(
    bool Success,
    bool IncludeUnknownsSection,
    bool DistilledNarrativeOnly,
    bool IncludeAskedQuestionsAppendix,
    decimal DiscoveryCompletenessScore,
    string DecisionReason,
    List<string> UnknownTopics,
    string UnknownsSectionText,
    string? ErrorCode = null,
    string? ErrorMessage = null);

public interface ISummaryCompositionPolicyService
{
    Task<EvaluateSummaryCompositionResult> EvaluateAsync(EvaluateSummaryCompositionRequest request);
}

public class SummaryCompositionPolicyService(IPresaleLeadRepository repository) : ISummaryCompositionPolicyService
{
    public async Task<EvaluateSummaryCompositionResult> EvaluateAsync(EvaluateSummaryCompositionRequest request)
    {
        var lead = await repository.GetPresaleLeadAsync(request.LeadId);
        if (lead is null)
        {
            return new EvaluateSummaryCompositionResult(
                Success: false,
                IncludeUnknownsSection: false,
                DistilledNarrativeOnly: true,
                IncludeAskedQuestionsAppendix: false,
                DiscoveryCompletenessScore: 0m,
                DecisionReason: "lead_not_found",
                UnknownTopics: [],
                UnknownsSectionText: string.Empty,
                ErrorCode: "LEAD_NOT_FOUND",
                ErrorMessage: "Presale lead was not found.");
        }

        var score = decimal.Clamp(lead.DiscoveryCompletenessScore, 0m, 1m);
        var pendingTopics = ParsePendingTopics(lead.PendingDiscoveryItemsJson)
            .Take(Math.Max(1, request.MaxUnknownTopics))
            .ToList();

        var reasonTokens = ParseReasonTokens(lead.DiscoveryCompletenessReason);
        var hasUnknownsRequiredToken = reasonTokens.Contains("unknowns_required");
        var hasConfirmationUnavailableToken = reasonTokens.Contains("confirmation_unavailable");

        var diagnosticsRequireUnknowns = pendingTopics.Count > 0
                                         && hasConfirmationUnavailableToken
                                         && score < request.UnknownsCompletenessThreshold;

        var includeUnknowns = pendingTopics.Count > 0 && (hasUnknownsRequiredToken || diagnosticsRequireUnknowns);

        var decisionReason = includeUnknowns
            ? hasUnknownsRequiredToken
                ? "required_by_unknowns_token"
                : "required_by_diagnostics_threshold"
            : "not_required";

        return new EvaluateSummaryCompositionResult(
            Success: true,
            IncludeUnknownsSection: includeUnknowns,
            DistilledNarrativeOnly: true,
            IncludeAskedQuestionsAppendix: false,
            DiscoveryCompletenessScore: score,
            DecisionReason: decisionReason,
            UnknownTopics: includeUnknowns ? pendingTopics : [],
            UnknownsSectionText: includeUnknowns ? BuildUnknownsSection(pendingTopics) : string.Empty);
    }

    private static HashSet<string> ParseReasonTokens(string? reason)
    {
        if (string.IsNullOrWhiteSpace(reason))
        {
            return [];
        }

        return reason.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
                     .Select(x => x.Trim().ToLowerInvariant())
                     .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    private static List<string> ParsePendingTopics(string? pendingTopicsJson)
    {
        if (string.IsNullOrWhiteSpace(pendingTopicsJson))
        {
            return [];
        }

        try
        {
            var topics = JsonSerializer.Deserialize<List<string>>(pendingTopicsJson) ?? [];

            return topics.Where(x => !string.IsNullOrWhiteSpace(x))
                         .Select(x => x.Trim().ToLowerInvariant())
                         .Distinct(StringComparer.OrdinalIgnoreCase)
                         .ToList();
        }
        catch
        {
            return [];
        }
    }

    private static string BuildUnknownsSection(IEnumerable<string> topics)
    {
        var lines = topics.Select(x => $"- {x}").ToList();
        if (lines.Count == 0)
        {
            return string.Empty;
        }

        return "Unknowns\n" + string.Join(Environment.NewLine, lines);
    }
}
