// Generated by GitHub Copilot on 2026-03-30
using System.Text.Json;

namespace InterviewCoach.Agent;

public static class DiscoveryPayloadBuilder
{
    public static string BuildInitialDiscoveryBatch(string proposedQuestionsJson, string askedQuestionsJson, int maxQuestions = DiscoveryFlowLimits.InitialBatchSize)
    {
        if (string.IsNullOrWhiteSpace(proposedQuestionsJson))
        {
            return "[]";
        }

        try
        {
            var proposedQuestions = JsonSerializer.Deserialize<List<ProposedInitialQuestionContract>>(proposedQuestionsJson, SerializerOptions) ?? [];
            var askedQuestions = string.IsNullOrWhiteSpace(askedQuestionsJson)
                ? []
                : JsonSerializer.Deserialize<List<AskedQuestionContract>>(askedQuestionsJson, SerializerOptions) ?? [];

            var existingTopicKeys = askedQuestions
                .Select(x => NormalizeTopicKey(x.QuestionTopicKey))
                .ToHashSet(StringComparer.OrdinalIgnoreCase);
            var maxSelectedCount = Math.Max(1, maxQuestions);

            var selectedQuestions = new List<SelectedInitialQuestionContract>();
            foreach (var question in proposedQuestions)
            {
                if (string.IsNullOrWhiteSpace(question.QuestionText))
                {
                    continue;
                }

                var normalizedTopicKey = NormalizeTopicKey(question.QuestionTopicKey);
                if (!existingTopicKeys.Add(normalizedTopicKey))
                {
                    continue;
                }

                selectedQuestions.Add(new SelectedInitialQuestionContract(
                    QuestionText: question.QuestionText.Trim(),
                    QuestionTopicKey: normalizedTopicKey));

                if (selectedQuestions.Count >= maxSelectedCount)
                {
                    break;
                }
            }

            return JsonSerializer.Serialize(selectedQuestions, SerializerOptions);
        }

        catch (Exception ex) 
        { 
            throw new InvalidOperationException("Failed to build initial discovery batch.", ex);
        }
    }

    public static string BuildAddDiscoveryQuestionPayloads(string parseDiscoveryReplyResultJson, string askedQuestionsJson)
    {
        if (string.IsNullOrWhiteSpace(parseDiscoveryReplyResultJson) || string.IsNullOrWhiteSpace(askedQuestionsJson))
        {
            return "[]";
        }

        var parseResult = JsonSerializer.Deserialize<ParseDiscoveryReplyResultContract>(parseDiscoveryReplyResultJson, SerializerOptions);
        var askedQuestions = JsonSerializer.Deserialize<List<AskedQuestionContract>>(askedQuestionsJson, SerializerOptions) ?? [];
        if (parseResult is null || parseResult.Success is false || parseResult.Items is null || parseResult.Items.Count == 0)
        {
            return "[]";
        }

        var askedQuestionById = askedQuestions
            .Where(x => x.Id != Guid.Empty)
            .GroupBy(x => x.Id)
            .ToDictionary(x => x.Key, x => x.First());

        var payloads = new List<AddDiscoveryQuestionPayload>();
        foreach (var item in parseResult.Items.OrderBy(x => x.Number))
        {
            if (item.AskedQuestionIds is null || item.AskedQuestionIds.Count == 0)
            {
                continue;
            }

            foreach (var askedQuestionId in item.AskedQuestionIds)
            {
                if (!askedQuestionById.TryGetValue(askedQuestionId, out var askedQuestion))
                {
                    continue;
                }

                payloads.Add(new AddDiscoveryQuestionPayload(
                    AskedQuestionId: askedQuestion.Id,
                    Question: askedQuestion.QuestionText,
                    Answer: item.Answer,
                    QuestionKind: string.IsNullOrWhiteSpace(askedQuestion.QuestionKind) ? "Initial" : askedQuestion.QuestionKind,
                    RoundNumber: Math.Max(0, askedQuestion.RoundNumber),
                    ParentAskedQuestionId: askedQuestion.ParentAskedQuestionId,
                    CoverageTopicKeys: SerializeCoverageTopicKeys(item.CoverageTopicKeys, askedQuestion.QuestionTopicKey)));
            }
        }

        return JsonSerializer.Serialize(payloads, SerializerOptions);
    }

    private static string NormalizeTopicKey(string? topicKey)
    {
        return string.IsNullOrWhiteSpace(topicKey)
            ? "unknown"
            : topicKey.Trim().ToLowerInvariant();
    }

    private static string SerializeCoverageTopicKeys(List<string>? coverageTopicKeys, string askedQuestionTopicKey)
    {
        var normalizedKeys = coverageTopicKeys is { Count: > 0 }
            ? coverageTopicKeys.Distinct(StringComparer.OrdinalIgnoreCase).ToList()
            : new List<string> { NormalizeTopicKey(askedQuestionTopicKey) };

        return JsonSerializer.Serialize(normalizedKeys);
    }

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = false
    };

    private sealed record ParseDiscoveryReplyResultContract(bool Success, List<ParsedItemContract> Items);

    private sealed record ParsedItemContract(int Number, string Answer, List<Guid> AskedQuestionIds, List<string> CoverageTopicKeys);

    private sealed record ProposedInitialQuestionContract(
        string QuestionText,
        string QuestionTopicKey);

    private sealed record SelectedInitialQuestionContract(
        string QuestionText,
        string QuestionTopicKey);

    private sealed record AskedQuestionContract(
        Guid Id,
        string QuestionText,
        string QuestionKind,
        int RoundNumber,
        Guid? ParentAskedQuestionId,
        string QuestionTopicKey);

    private sealed record AddDiscoveryQuestionPayload(
        Guid AskedQuestionId,
        string Question,
        string Answer,
        string QuestionKind,
        int RoundNumber,
        Guid? ParentAskedQuestionId,
        string CoverageTopicKeys);
}
