// Generated by GitHub Copilot on 2026-03-29
using System.Collections.Concurrent;

using InterviewCoach.Agent;

using Microsoft.Agents.AI;
using Microsoft.Agents.AI.DevUI;
using Microsoft.Agents.AI.Hosting.AGUI.AspNetCore;
using Microsoft.Extensions.AI;

using ModelContextProtocol.Client;
using ModelContextProtocol.Protocol;

var builder = WebApplication.CreateBuilder(args);
var config = builder.Configuration;

builder.AddServiceDefaults();

builder.Services.AddHttpClient("mcp-markitdown", client =>
{
    client.BaseAddress = new Uri("https+http://mcp-markitdown");
});

builder.Services.AddKeyedSingleton<McpClient>("mcp-markitdown", (sp, obj) =>
{
    var loggerFactory = sp.GetRequiredService<ILoggerFactory>();
    var httpClient = sp.GetRequiredService<IHttpClientFactory>()
                       .CreateClient("mcp-markitdown");
    var env = sp.GetRequiredService<Microsoft.Extensions.Hosting.IHostEnvironment>();
    var baseAddressString = httpClient.BaseAddress?.ToString() ?? throw new InvalidOperationException("HttpClient BaseAddress is not set.");

    // The BaseAddress in this project may use a marker prefix like "https+http://host" to
    // indicate environment-specific scheme. Normalize it based on the current environment
    // then construct a proper Uri using the Uri APIs instead of string concatenation.
    var normalizedBase = env.IsDevelopment()
                         ? baseAddressString.Replace("https+", string.Empty)
                         : baseAddressString.Replace("+http", string.Empty);

    var baseUri = new Uri(normalizedBase.TrimEnd('/'));

    var clientTransportOptions = new HttpClientTransportOptions()
    {
        Endpoint = new Uri(baseUri, "sse")
    };
    var clientTransport = new HttpClientTransport(clientTransportOptions, httpClient, loggerFactory);

    var clientOptions = new McpClientOptions()
    {
        ClientInfo = new Implementation()
        {
            Name = "MCP MarkItDown Client",
            Version = "1.0.0",
        }
    };

    return McpClient.CreateAsync(clientTransport, clientOptions, loggerFactory).GetAwaiter().GetResult();
});


//builder.Services.AddHttpClient("mcp-interview-data", client =>
//{
//    client.BaseAddress = new Uri("https+http://mcp-interview-data");
//});

builder.Services.AddHttpClient("mcp-presale-assistant-data", client =>
{
    client.BaseAddress = new Uri("https+http://mcp-presale-assistant-data");
});

//builder.Services.AddKeyedSingleton<McpClient>("mcp-interview-data", (sp, obj) =>
//{
//    return CreateMcpDataClient(sp, "mcp-interview-data", "MCP Interview Data Client");
//});

builder.Services.AddKeyedSingleton<McpClient>("mcp-presale-assistant-data", (sp, obj) =>
{
    return CreateMcpDataClient(sp, "mcp-presale-assistant-data", "MCP Presale Assistant Data Client");
});

static McpClient CreateMcpDataClient(IServiceProvider serviceProvider, string clientName, string implementationName)
{
    var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
    var httpClient = serviceProvider.GetRequiredService<IHttpClientFactory>()
                                    .CreateClient(clientName);

    var baseAddress = httpClient.BaseAddress ?? throw new InvalidOperationException("HttpClient BaseAddress is not set.");

    // Normalize any marker prefixes used for environment-specific scheme selection and
    // construct the endpoint using Uri APIs to avoid fragile string manipulation.
    var baseAddressString = baseAddress.ToString();
    var env = serviceProvider.GetRequiredService<Microsoft.Extensions.Hosting.IHostEnvironment>();
    var normalizedBase = env.IsDevelopment()
                         ? baseAddressString.Replace("https+", string.Empty)
                         : baseAddressString.Replace("+http", string.Empty);

    var baseUri = new Uri(normalizedBase.TrimEnd('/'));

    var clientTransportOptions = new HttpClientTransportOptions()
    {
        Endpoint = new Uri(baseUri, "mcp")
    };
    var clientTransport = new HttpClientTransport(clientTransportOptions, httpClient, loggerFactory);

    var clientOptions = new McpClientOptions()
    {
        ClientInfo = new Implementation()
        {
            Name = implementationName,
            Version = "1.0.0",
        }
    };

    return McpClient.CreateAsync(clientTransport, clientOptions, loggerFactory).GetAwaiter().GetResult();
}

if (config[Constants.LlmProvider] != "MicrosoftFoundry")
{
    builder.AddOpenAIClient("chat")
           .AddChatClient();
}
else
{
    builder.AddOpenAIClient("chat")
           .AddChatClient();

    // var connection = new DbConnectionStringBuilder() { ConnectionString = config.GetConnectionString("foundry") };
    // var endpoint = connection.TryGetValue("Endpoint", out var endpointValue) ? endpointValue?.ToString() : throw new InvalidOperationException("Missing Foundry Endpoint");
    // // var accessKey = connection.TryGetValue("Key", out var accessKeyValue) ? accessKeyValue?.ToString() : throw new InvalidOperationException("Missing Foundry Key");
    // var model = connection.TryGetValue("Model", out var modelValue) ? modelValue?.ToString() : throw new InvalidOperationException("Missing Foundry Model");
    // var options = new OpenAIClientOptions() { Endpoint = new Uri(endpoint!) };
    // var credential = new DefaultAzureCredential();
    // var client = new OpenAIClient(new BearerTokenPolicy(credential, "https://ai.azure.com/.default"), options)
    //                 .GetResponsesClient(model!)
    //                 .AsIChatClient();

    // builder.Services.AddSingleton<IChatClient>(client);
}

builder.AddAIAgent("coach");

builder.Services.AddOpenAIResponses();
builder.Services.AddOpenAIConversations();

builder.Services.AddAGUI();

var app = builder.Build();

app.MapDefaultEndpoints();

app.MapOpenAIResponses();
app.MapOpenAIConversations();

app.MapAGUI(
    pattern: "ag-ui",
    aiAgent: app.Services.GetRequiredKeyedService<AIAgent>("coach")
);

if (builder.Environment.IsDevelopment() == false)
{
    app.UseHttpsRedirection();
}
else
{
    app.MapDevUI();
}

// --- File Upload Endpoints ---
// In-memory store for uploaded files (ephemeral, session-scoped).
var uploadedFiles = new ConcurrentDictionary<string, (byte[] Content, string ContentType, string FileName)>();

var allowedExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    ".pdf", ".docx", ".doc", ".txt", ".md", ".html"
};

app.MapPost("/upload", async (HttpRequest request) =>
{
    if (!request.HasFormContentType)
        return Results.BadRequest("Expected multipart/form-data.");

    var form = await request.ReadFormAsync();
    var file = form.Files.GetFile("file");

    if (file is null || file.Length == 0)
        return Results.BadRequest("No file provided.");

    if (file.Length > 10 * 1024 * 1024)
        return Results.Problem("File size exceeds 10 MB limit.", statusCode: 413);

    var ext = Path.GetExtension(file.FileName);
    if (!allowedExtensions.Contains(ext))
        return Results.Problem($"File type '{ext}' is not supported.", statusCode: 415);

    var fileId = Guid.NewGuid().ToString("N");
    using var ms = new MemoryStream();
    await file.CopyToAsync(ms);

    uploadedFiles[fileId] = (ms.ToArray(), file.ContentType, file.FileName);

    var url = $"{request.Scheme}://{request.Host}/uploads/{fileId}/{Uri.EscapeDataString(file.FileName)}";
    return Results.Ok(new { url });
});

app.MapGet("/uploads/{fileId}/{fileName}", (string fileId, string fileName) =>
{
    if (!uploadedFiles.TryGetValue(fileId, out var entry))
        return Results.NotFound();

    return Results.File(entry.Content, entry.ContentType, entry.FileName);
});

await app.RunAsync();