// Generated by GitHub Copilot on 2026-03-29
namespace InterviewCoach.Shared.Infrastructure;

public static class SqliteResourceNames
{
    public const string InterviewDataResourceName = "sqlite-interview-data";
    public const string InterviewDataDatabaseFileName = "interviewcoach-interview-data.db";
    public const string PresaleDataResourceName = "sqlite-presale-assistant-data";
    public const string PresaleDataDatabaseFileName = "interviewcoach-presale-data.db";
}