// Generated by GitHub Copilot on 2026-03-29
namespace InterviewCoach.Shared.Presale;

public enum RequestType
{
    Unknown,
    Other,
    CustomSoftwareDevelopment,
    OffshoreDevelopment,
    Modernization,
    AIIntegration,
    CloudMigration,
    SystemIntegration,
    MobileAppDevelopment,
    WebApplication,
    APIDevelopment,
    DevOpsAutomation,
    LegacyModernization,
    TechnicalAudit,
    StaffAugmentation,
    CloudOptimization,
    ITConsulting
}