// Generated by GitHub Copilot on 2026-03-15
namespace InterviewCoach.WebUI.Services;

public sealed record ServiceCardItem
{
    public string Icon { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
}

public sealed record ServicesData
{
    public string Description { get; init; } = string.Empty;
    public string[] Skills { get; init; } = [];
    public string DetailOrQuote { get; init; } = string.Empty;
    public ServiceCardItem[] Cards { get; init; } = [];
}

public sealed record TechnologyBand
{
    public string Label { get; init; } = string.Empty;
    public string[] Technologies { get; init; } = [];
}

public sealed record TechnologiesData
{
    public TechnologyBand[] Bands { get; init; } = [];
}