// Generated by GitHub Copilot on 2026-03-15
namespace InterviewCoach.WebUI.Services;

public sealed record SiteProperties(
    string Name,
    string Title,
    string Email,
    string? DevDotTo,
    string? GitHub,
    string? Instagram,
    string? LinkedIn,
    string? Medium,
    string? Twitter,
    string? YouTube
);
