// Generated by GitHub Copilot on 2026-03-29

var builder = DistributedApplication.CreateBuilder(args);

// var foundry = builder.AddBicepTemplate("foundry", "../../infra/foundry.bicep");

var mcpMarkItDown = builder.AddContainer(ResourceConstants.McpMarkItDown, "mcp/markitdown", "latest")
                           .WithExternalHttpEndpoints()
                           .WithHttpEndpoint(3001, 3001)
                           .WithArgs("--http", "--host", "0.0.0.0", "--port", "3001");

//var interviewDataSqlite = builder.AddSqlite(ResourceConstants.InterviewDataResourceName, 
//                                            databaseFileName: ResourceConstants.InterviewDataDatabaseFileName);

var presaleDataSqlite = builder.AddSqlite(ResourceConstants.PresaleDataResourceName,
                                          databaseFileName: ResourceConstants.PresaleDataDatabaseFileName);

//var mcpInterviewData = builder.AddProject<Projects.InterviewCoach_Mcp_InterviewData>(ResourceConstants.McpInterviewData)
//                              .WithExternalHttpEndpoints()
//                              .WithReference(interviewDataSqlite)
//                              .WaitFor(interviewDataSqlite);

var mcpPresaleData = builder.AddProject<Projects.InterviewCoach_Mcp_PresaleData>(ResourceConstants.McpPresaleData)
                            .WithExternalHttpEndpoints()
                            .WithReference(presaleDataSqlite)
                            .WaitFor(presaleDataSqlite);

//interviewDataSqlite.WithSqliteWeb(c => c.WaitFor(mcpInterviewData));
presaleDataSqlite.WithSqliteWeb(c => c.WaitFor(mcpPresaleData));

var agent = builder.AddProject<Projects.InterviewCoach_Agent>(ResourceConstants.Agent)
                   .WithExternalHttpEndpoints()
                   .WithLlmReference(builder.Configuration, args)
                   .WithEnvironment(ResourceConstants.LlmProvider, builder.Configuration[ResourceConstants.LlmProvider] ?? string.Empty)
                   .WithReference(mcpMarkItDown.GetEndpoint("http"))
                   //.WithReference(mcpInterviewData)
                   .WithReference(mcpPresaleData)
                   .WaitFor(mcpMarkItDown)
                   //.WaitFor(mcpInterviewData);
                   .WaitFor(mcpPresaleData);

var webUI = builder.AddProject<Projects.InterviewCoach_WebUI>(ResourceConstants.WebUI)
                   .WithExternalHttpEndpoints()
                   .WithReference(agent)
                   .WaitFor(agent);

await builder.Build().RunAsync();