// Generated by GitHub Copilot on 2026-03-29
public class ResourceConstants
{
    public const string LlmProvider = "LlmProvider";
    public const string McpMarkItDown = "mcp-markitdown";
    public const string McpInterviewData = "mcp-interview-data";
    public const string McpPresaleData = "mcp-presale-assistant-data";
    public const string Agent = "agent";
    public const string WebUI = "webui";
    public const string InterviewDataResourceName = "sqlite-interview-data";
    public const string InterviewDataDatabaseFileName = "interviewcoach-interview-data.db";
    public const string PresaleDataResourceName = "sqlite-presale-assistant-data";
    public const string PresaleDataDatabaseFileName = "interviewcoach-presale-assistant-data.db";
}